// ===== CATÁLOGO COMPLETO DE OBJETOS (Gen 1-5) - Parte 2: Objetos generales y equipables =====

export const OBJETOS_ITEMS = [
  // Repelentes y utilidad
  { id: 'escape-rope', name: 'Cuerda Huida', sprite: 'escape-rope', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Huye de cuevas' },
  { id: 'repel', name: 'Repelente', sprite: 'repel', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Repele Pokémon 100 pasos' },
  { id: 'super-repel', name: 'Superrepel', sprite: 'super-repel', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Repele Pokémon 200 pasos' },
  { id: 'max-repel', name: 'Repel Máximo', sprite: 'max-repel', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Repele Pokémon 250 pasos' },
  { id: 'honey', name: 'Miel', sprite: 'honey', pocket: 'objetos', gens: [4,5], effect: 'Atrae Pokémon salvajes' },
  // Piedras evolutivas
  { id: 'fire-stone', name: 'Piedra Fuego', sprite: 'fire-stone', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Evoluciona ciertos Pokémon' },
  { id: 'water-stone', name: 'Piedra Agua', sprite: 'water-stone', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Evoluciona ciertos Pokémon' },
  { id: 'thunder-stone', name: 'Piedra Trueno', sprite: 'thunder-stone', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Evoluciona ciertos Pokémon' },
  { id: 'leaf-stone', name: 'Piedra Hoja', sprite: 'leaf-stone', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Evoluciona ciertos Pokémon' },
  { id: 'moon-stone', name: 'Piedra Lunar', sprite: 'moon-stone', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Evoluciona ciertos Pokémon' },
  { id: 'sun-stone', name: 'Piedra Solar', sprite: 'sun-stone', pocket: 'objetos', gens: [2,3,4,5], effect: 'Evoluciona ciertos Pokémon' },
  { id: 'shiny-stone', name: 'Piedra Día', sprite: 'shiny-stone', pocket: 'objetos', gens: [4,5], effect: 'Evoluciona ciertos Pokémon' },
  { id: 'dusk-stone', name: 'Piedra Noche', sprite: 'dusk-stone', pocket: 'objetos', gens: [4,5], effect: 'Evoluciona ciertos Pokémon' },
  { id: 'dawn-stone', name: 'Piedra Alba', sprite: 'dawn-stone', pocket: 'objetos', gens: [4,5], effect: 'Evoluciona ciertos Pokémon' },
  { id: 'oval-stone', name: 'Piedra Oval', sprite: 'oval-stone', pocket: 'objetos', gens: [4,5], effect: 'Happiny evoluciona a Chansey' },
  // Objetos de evolución por intercambio
  { id: 'kings-rock', name: 'Roca del Rey', sprite: 'kings-rock', pocket: 'objetos', gens: [2,3,4,5], effect: 'Evol. Poliwhirl/Slowpoke al interc.' },
  { id: 'metal-coat', name: 'Revestimiento Met.', sprite: 'metal-coat', pocket: 'objetos', gens: [2,3,4,5], effect: 'Evol. Onix/Scyther al intercambiar' },
  { id: 'dragon-scale', name: 'Escama Dragón', sprite: 'dragon-scale', pocket: 'objetos', gens: [2,3,4,5], effect: 'Evol. Seadra al intercambiar' },
  { id: 'up-grade', name: 'Mejora', sprite: 'up-grade', pocket: 'objetos', gens: [2,3,4,5], effect: 'Evol. Porygon al intercambiar' },
  { id: 'deep-sea-tooth', name: 'Diente Marino', sprite: 'deep-sea-tooth', pocket: 'objetos', gens: [3,4,5], effect: 'Evol. Clamperl a Huntail' },
  { id: 'deep-sea-scale', name: 'Escama Marina', sprite: 'deep-sea-scale', pocket: 'objetos', gens: [3,4,5], effect: 'Evol. Clamperl a Gorebyss' },
  { id: 'protector', name: 'Protector', sprite: 'protector', pocket: 'objetos', gens: [4,5], effect: 'Evol. Rhydon al intercambiar' },
  { id: 'electirizer', name: 'Electrizador', sprite: 'electirizer', pocket: 'objetos', gens: [4,5], effect: 'Evol. Electabuzz al intercambiar' },
  { id: 'magmarizer', name: 'Magmatizador', sprite: 'magmarizer', pocket: 'objetos', gens: [4,5], effect: 'Evol. Magmar al intercambiar' },
  { id: 'dubious-disc', name: 'Disco Extraño', sprite: 'dubious-disc', pocket: 'objetos', gens: [4,5], effect: 'Evol. Porygon2 al intercambiar' },
  { id: 'reaper-cloth', name: 'Tela Terrible', sprite: 'reaper-cloth', pocket: 'objetos', gens: [4,5], effect: 'Evol. Dusclops al intercambiar' },
  { id: 'razor-claw', name: 'Garra Afilada', sprite: 'razor-claw', pocket: 'objetos', gens: [4,5], effect: 'Evol. Sneasel de noche' },
  { id: 'razor-fang', name: 'Colmillo Afilado', sprite: 'razor-fang', pocket: 'objetos', gens: [4,5], effect: 'Evol. Gligar de noche' },
  { id: 'prism-scale', name: 'Escama Prisma', sprite: 'prism-scale', pocket: 'objetos', gens: [5], effect: 'Evol. Feebas al intercambiar' },
  // Vitaminas
  { id: 'hp-up', name: 'Más PS', sprite: 'hp-up', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Sube EV de PS' },
  { id: 'protein', name: 'Proteína', sprite: 'protein', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Sube EV de Ataque' },
  { id: 'iron', name: 'Hierro', sprite: 'iron', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Sube EV de Defensa' },
  { id: 'calcium', name: 'Calcio', sprite: 'calcium', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Sube EV de At. Especial' },
  { id: 'zinc', name: 'Zinc', sprite: 'zinc', pocket: 'objetos', gens: [2,3,4,5], effect: 'Sube EV de Def. Especial' },
  { id: 'carbos', name: 'Carburante', sprite: 'carbos', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Sube EV de Velocidad' },
  { id: 'pp-up', name: 'Más PP', sprite: 'pp-up', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Sube PP máx. de un movimiento' },
  { id: 'pp-max', name: 'PP Máximo', sprite: 'pp-max', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Maximiza PP de un movimiento' },
  // Alas (Gen 5)
  { id: 'health-wing', name: 'Pluma Vigor', sprite: 'health-wing', pocket: 'objetos', gens: [5], effect: '+1 EV de PS' },
  { id: 'muscle-wing', name: 'Pluma Músculo', sprite: 'muscle-wing', pocket: 'objetos', gens: [5], effect: '+1 EV de Ataque' },
  { id: 'resist-wing', name: 'Pluma Aguante', sprite: 'resist-wing', pocket: 'objetos', gens: [5], effect: '+1 EV de Defensa' },
  { id: 'genius-wing', name: 'Pluma Genio', sprite: 'genius-wing', pocket: 'objetos', gens: [5], effect: '+1 EV de At. Especial' },
  { id: 'clever-wing', name: 'Pluma Astucia', sprite: 'clever-wing', pocket: 'objetos', gens: [5], effect: '+1 EV de Def. Especial' },
  { id: 'swift-wing', name: 'Pluma Rapidez', sprite: 'swift-wing', pocket: 'objetos', gens: [5], effect: '+1 EV de Velocidad' },
  // Objetos de venta
  { id: 'nugget', name: 'Pepita', sprite: 'nugget', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Se vende por 5000₽' },
  { id: 'big-nugget', name: 'Pepita Grande', sprite: 'big-nugget', pocket: 'objetos', gens: [5], effect: 'Se vende por 10000₽' },
  { id: 'pearl', name: 'Perla', sprite: 'pearl', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Se vende por 700₽' },
  { id: 'big-pearl', name: 'Perla Grande', sprite: 'big-pearl', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Se vende por 3750₽' },
  { id: 'pearl-string', name: 'Collar de Perlas', sprite: 'pearl-string', pocket: 'objetos', gens: [5], effect: 'Se vende por 12500₽' },
  { id: 'stardust', name: 'Polvo Estelar', sprite: 'stardust', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Se vende por 1000₽' },
  { id: 'star-piece', name: 'Trozo Estrella', sprite: 'star-piece', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Se vende por 4900₽' },
  { id: 'comet-shard', name: 'Trozo Cometa', sprite: 'comet-shard', pocket: 'objetos', gens: [5], effect: 'Se vende por 25000₽' },
  { id: 'tiny-mushroom', name: 'Miniseta', sprite: 'tiny-mushroom', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Se vende por 250₽' },
  { id: 'big-mushroom', name: 'Seta Grande', sprite: 'big-mushroom', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'Se vende por 2500₽' },
  { id: 'balm-mushroom', name: 'Seta Aroma', sprite: 'balm-mushroom', pocket: 'objetos', gens: [5], effect: 'Se vende por 6250₽' },
  { id: 'rare-bone', name: 'Hueso Raro', sprite: 'rare-bone', pocket: 'objetos', gens: [4,5], effect: 'Se vende por 5000₽' },
  { id: 'heart-scale', name: 'Escama Corazón', sprite: 'heart-scale', pocket: 'objetos', gens: [3,4,5], effect: 'Recuerda movimientos' },
  // Fragmentos
  { id: 'red-shard', name: 'Trozo Rojo', sprite: 'red-shard', pocket: 'objetos', gens: [3,4,5], effect: 'Se intercambia por objetos' },
  { id: 'blue-shard', name: 'Trozo Azul', sprite: 'blue-shard', pocket: 'objetos', gens: [3,4,5], effect: 'Se intercambia por objetos' },
  { id: 'yellow-shard', name: 'Trozo Amarillo', sprite: 'yellow-shard', pocket: 'objetos', gens: [3,4,5], effect: 'Se intercambia por objetos' },
  { id: 'green-shard', name: 'Trozo Verde', sprite: 'green-shard', pocket: 'objetos', gens: [3,4,5], effect: 'Se intercambia por objetos' },
  // Flautas (Gen 3)
  { id: 'blue-flute', name: 'Flauta Azul', sprite: 'blue-flute', pocket: 'objetos', gens: [3,4,5], effect: 'Despierta al Pokémon' },
  { id: 'yellow-flute', name: 'Flauta Amarilla', sprite: 'yellow-flute', pocket: 'objetos', gens: [3,4,5], effect: 'Cura confusión' },
  { id: 'red-flute', name: 'Flauta Roja', sprite: 'red-flute', pocket: 'objetos', gens: [3,4,5], effect: 'Cura enamoramiento' },
  { id: 'black-flute', name: 'Flauta Negra', sprite: 'black-flute', pocket: 'objetos', gens: [3,4,5], effect: 'Reduce encuentros salvajes' },
  { id: 'white-flute', name: 'Flauta Blanca', sprite: 'white-flute', pocket: 'objetos', gens: [3,4,5], effect: 'Aumenta encuentros salvajes' },
  // Fósiles
  { id: 'helix-fossil', name: 'Fósil Helix', sprite: 'helix-fossil', pocket: 'objetos', gens: [1,3,4,5], effect: 'Revive a Omanyte' },
  { id: 'dome-fossil', name: 'Fósil Domo', sprite: 'dome-fossil', pocket: 'objetos', gens: [1,3,4,5], effect: 'Revive a Kabuto' },
  { id: 'old-amber', name: 'Ámbar Viejo', sprite: 'old-amber', pocket: 'objetos', gens: [1,3,4,5], effect: 'Revive a Aerodactyl' },
  { id: 'root-fossil', name: 'Fósil Raíz', sprite: 'root-fossil', pocket: 'objetos', gens: [3,4,5], effect: 'Revive a Lileep' },
  { id: 'claw-fossil', name: 'Fósil Garra', sprite: 'claw-fossil', pocket: 'objetos', gens: [3,4,5], effect: 'Revive a Anorith' },
  { id: 'armor-fossil', name: 'Fósil Coraza', sprite: 'armor-fossil', pocket: 'objetos', gens: [4,5], effect: 'Revive a Shieldon' },
  { id: 'skull-fossil', name: 'Fósil Cráneo', sprite: 'skull-fossil', pocket: 'objetos', gens: [4,5], effect: 'Revive a Cranidos' },
  { id: 'cover-fossil', name: 'Fósil Tapa', sprite: 'cover-fossil', pocket: 'objetos', gens: [5], effect: 'Revive a Tirtouga' },
  { id: 'plume-fossil', name: 'Fósil Pluma', sprite: 'plume-fossil', pocket: 'objetos', gens: [5], effect: 'Revive a Archen' },
  // Shoal y Reliquias
  { id: 'shoal-salt', name: 'Sal Cardumen', sprite: 'shoal-salt', pocket: 'objetos', gens: [3,4,5], effect: 'Para hacer Campana Concha' },
  { id: 'shoal-shell', name: 'Concha Cardumen', sprite: 'shoal-shell', pocket: 'objetos', gens: [3,4,5], effect: 'Para hacer Campana Concha' },
  { id: 'relic-copper', name: 'Reliquia Cobre', sprite: 'relic-copper', pocket: 'objetos', gens: [5], effect: 'Tesoro antiguo: 1000₽' },
  { id: 'relic-silver', name: 'Reliquia Plata', sprite: 'relic-silver', pocket: 'objetos', gens: [5], effect: 'Tesoro antiguo: 5000₽' },
  { id: 'relic-gold', name: 'Reliquia Oro', sprite: 'relic-gold', pocket: 'objetos', gens: [5], effect: 'Tesoro antiguo: 10000₽' },
  { id: 'relic-vase', name: 'Reliquia Jarrón', sprite: 'relic-vase', pocket: 'objetos', gens: [5], effect: 'Tesoro antiguo: 50000₽' },
  { id: 'relic-band', name: 'Reliquia Banda', sprite: 'relic-band', pocket: 'objetos', gens: [5], effect: 'Tesoro antiguo: 100000₽' },
  { id: 'relic-statue', name: 'Reliquia Estatua', sprite: 'relic-statue', pocket: 'objetos', gens: [5], effect: 'Tesoro antiguo: 200000₽' },
  { id: 'relic-crown', name: 'Reliquia Corona', sprite: 'relic-crown', pocket: 'objetos', gens: [5], effect: 'Tesoro antiguo: 300000₽' },
  // Held Items - Competitivo / Utilidad
  { id: 'leftovers', name: 'Restos', sprite: 'leftovers', pocket: 'objetos', gens: [2,3,4,5], effect: 'Recupera 1/16 PS por turno' },
  { id: 'shell-bell', name: 'Campana Concha', sprite: 'shell-bell', pocket: 'objetos', gens: [3,4,5], effect: 'Recupera PS al dañar' },
  { id: 'lucky-egg', name: 'Huevo Suerte', sprite: 'lucky-egg', pocket: 'objetos', gens: [2,3,4,5], effect: '+50% experiencia' },
  { id: 'amulet-coin', name: 'Moneda Amuleto', sprite: 'amulet-coin', pocket: 'objetos', gens: [2,3,4,5], effect: 'Dobla dinero ganado' },
  { id: 'exp-share', name: 'Repartir Exp.', sprite: 'exp-share', pocket: 'objetos', gens: [2,3,4,5], effect: 'Comparte experiencia' },
  { id: 'everstone', name: 'Piedra Eterna', sprite: 'everstone', pocket: 'objetos', gens: [2,3,4,5], effect: 'Impide la evolución' },
  { id: 'smoke-ball', name: 'Bola Humo', sprite: 'smoke-ball', pocket: 'objetos', gens: [2,3,4,5], effect: 'Huida segura de salvajes' },
  { id: 'bright-powder', name: 'Polvo Brillo', sprite: 'bright-powder', pocket: 'objetos', gens: [2,3,4,5], effect: 'Reduce precisión rival' },
  { id: 'white-herb', name: 'Hierba Blanca', sprite: 'white-herb', pocket: 'objetos', gens: [3,4,5], effect: 'Restaura stats bajados (1 uso)' },
  { id: 'mental-herb', name: 'Hierba Mental', sprite: 'mental-herb', pocket: 'objetos', gens: [3,4,5], effect: 'Cura enamoramiento (1 uso)' },
  { id: 'power-herb', name: 'Hierba Única', sprite: 'power-herb', pocket: 'objetos', gens: [4,5], effect: 'Mov. en 2 turnos se hace en 1' },
  { id: 'macho-brace', name: 'Brazal Firme', sprite: 'macho-brace', pocket: 'objetos', gens: [3,4,5], effect: 'x2 EV ganados, -50% Velocidad' },
  { id: 'quick-claw', name: 'Garra Rápida', sprite: 'quick-claw', pocket: 'objetos', gens: [2,3,4,5], effect: '20% de atacar primero' },
  { id: 'soothe-bell', name: 'Campana Alivio', sprite: 'soothe-bell', pocket: 'objetos', gens: [3,4,5], effect: 'Aumenta felicidad ganada' },
  { id: 'cleanse-tag', name: 'Amuleto Puro', sprite: 'cleanse-tag', pocket: 'objetos', gens: [2,3,4,5], effect: 'Reduce encuentros salvajes' },
  { id: 'soul-dew', name: 'Rocío Bondad', sprite: 'soul-dew', pocket: 'objetos', gens: [3,4,5], effect: 'Potencia a Latios/Latias' },
  { id: 'scope-lens', name: 'Lupa', sprite: 'scope-lens', pocket: 'objetos', gens: [2,3,4,5], effect: 'Aumenta ratio de crítico' },
  { id: 'wide-lens', name: 'Lente Gran Angular', sprite: 'wide-lens', pocket: 'objetos', gens: [4,5], effect: '+10% precisión' },
  { id: 'zoom-lens', name: 'Lente Zoom', sprite: 'zoom-lens', pocket: 'objetos', gens: [4,5], effect: '+20% precisión si atacas último' },
  { id: 'muscle-band', name: 'Cinta Fuerte', sprite: 'muscle-band', pocket: 'objetos', gens: [4,5], effect: '+10% daño físico' },
  { id: 'wise-glasses', name: 'Gafas Especiales', sprite: 'wise-glasses', pocket: 'objetos', gens: [4,5], effect: '+10% daño especial' },
  { id: 'expert-belt', name: 'Cinta Experto', sprite: 'expert-belt', pocket: 'objetos', gens: [4,5], effect: '+20% daño superefectivo' },
  { id: 'life-orb', name: 'Vidasfera', sprite: 'life-orb', pocket: 'objetos', gens: [4,5], effect: '+30% daño, consume PS' },
  { id: 'choice-band', name: 'Cinta Elegida', sprite: 'choice-band', pocket: 'objetos', gens: [3,4,5], effect: '+50% Ataque, bloquea movs.' },
  { id: 'choice-specs', name: 'Gafas Elegidas', sprite: 'choice-specs', pocket: 'objetos', gens: [4,5], effect: '+50% At. Esp., bloquea movs.' },
  { id: 'choice-scarf', name: 'Pañuelo Elegido', sprite: 'choice-scarf', pocket: 'objetos', gens: [4,5], effect: '+50% Vel., bloquea movs.' },
  { id: 'focus-sash', name: 'Banda Focus', sprite: 'focus-sash', pocket: 'objetos', gens: [4,5], effect: 'Aguanta un golpe letal' },
  { id: 'focus-band', name: 'Cinta Focus', sprite: 'focus-band', pocket: 'objetos', gens: [2,3,4,5], effect: '10% de aguantar golpe letal' },
  { id: 'metronome', name: 'Metrónomo', sprite: 'metronome', pocket: 'objetos', gens: [4,5], effect: '+20% daño repetido' },
  { id: 'iron-ball', name: 'Bola de Hierro', sprite: 'iron-ball', pocket: 'objetos', gens: [4,5], effect: '-50% Vel., anula inmun. Tierra' },
  { id: 'lagging-tail', name: 'Cola Lenta', sprite: 'lagging-tail', pocket: 'objetos', gens: [4,5], effect: 'Ataca siempre último' },
  { id: 'destiny-knot', name: 'Lazo Destino', sprite: 'destiny-knot', pocket: 'objetos', gens: [4,5], effect: 'Pasa IVs al criar / contagia amor' },
  { id: 'black-sludge', name: 'Lodo Negro', sprite: 'black-sludge', pocket: 'objetos', gens: [4,5], effect: 'Veneno: +PS; otros: -PS' },
  { id: 'toxic-orb', name: 'Toxiesfera', sprite: 'toxic-orb', pocket: 'objetos', gens: [4,5], effect: 'Se envenena gravemente' },
  { id: 'flame-orb', name: 'Flamosfera', sprite: 'flame-orb', pocket: 'objetos', gens: [4,5], effect: 'Se quema al final del turno' },
  { id: 'light-clay', name: 'Roca Luz', sprite: 'light-clay', pocket: 'objetos', gens: [4,5], effect: 'Pantalla Luz/Reflejo dura 8 turnos' },
  { id: 'icy-rock', name: 'Roca Helada', sprite: 'icy-rock', pocket: 'objetos', gens: [4,5], effect: 'Granizo dura 8 turnos' },
  { id: 'smooth-rock', name: 'Roca Suave', sprite: 'smooth-rock', pocket: 'objetos', gens: [4,5], effect: 'Torm. Arena dura 8 turnos' },
  { id: 'heat-rock', name: 'Roca Caliente', sprite: 'heat-rock', pocket: 'objetos', gens: [4,5], effect: 'Sol dura 8 turnos' },
  { id: 'damp-rock', name: 'Roca Húmeda', sprite: 'damp-rock', pocket: 'objetos', gens: [4,5], effect: 'Lluvia dura 8 turnos' },
  { id: 'grip-claw', name: 'Garra Tenaza', sprite: 'grip-claw', pocket: 'objetos', gens: [4,5], effect: 'Ataques trampa 7 turnos' },
  { id: 'sticky-barb', name: 'Púas Adherentes', sprite: 'sticky-barb', pocket: 'objetos', gens: [4,5], effect: 'Quita PS, se pasa al rival' },
  { id: 'shed-shell', name: 'Muda Concha', sprite: 'shed-shell', pocket: 'objetos', gens: [4,5], effect: 'Permite cambiar siempre' },
  { id: 'big-root', name: 'Raíz Grande', sprite: 'big-root', pocket: 'objetos', gens: [4,5], effect: '+30% PS drenados' },
  // Gen 5 held items competitivos
  { id: 'eviolite', name: 'Mineral Evol.', sprite: 'eviolite', pocket: 'objetos', gens: [5], effect: '+50% Def/Def.Esp. si puede evolucionar' },
  { id: 'rocky-helmet', name: 'Casco Dentado', sprite: 'rocky-helmet', pocket: 'objetos', gens: [5], effect: 'Daña al rival que toca' },
  { id: 'air-balloon', name: 'Globo Helio', sprite: 'air-balloon', pocket: 'objetos', gens: [5], effect: 'Inmune a Tierra (1 uso)' },
  { id: 'red-card', name: 'Tarjeta Roja', sprite: 'red-card', pocket: 'objetos', gens: [5], effect: 'Fuerza cambio de rival (1 uso)' },
  { id: 'ring-target', name: 'Blanco', sprite: 'ring-target', pocket: 'objetos', gens: [5], effect: 'Elimina inmunidades de tipo' },
  { id: 'binding-band', name: 'Banda Atadura', sprite: 'binding-band', pocket: 'objetos', gens: [5], effect: 'Ataques trampa hacen más daño' },
  { id: 'absorb-bulb', name: 'Bulbo Absorbente', sprite: 'absorb-bulb', pocket: 'objetos', gens: [5], effect: '+1 At.Esp. si golpeado por Agua' },
  { id: 'cell-battery', name: 'Pila', sprite: 'cell-battery', pocket: 'objetos', gens: [5], effect: '+1 Ataque si golpeado por Eléctrico' },
  { id: 'eject-button', name: 'Botón Escape', sprite: 'eject-button', pocket: 'objetos', gens: [5], effect: 'Cambia al recibir daño (1 uso)' },
  { id: 'float-stone', name: 'Piedra Pómez', sprite: 'float-stone', pocket: 'objetos', gens: [5], effect: 'Reduce peso a la mitad' },
  // Potenciadores de tipo
  { id: 'silk-scarf', name: 'Pañuelo Seda', sprite: 'silk-scarf', pocket: 'objetos', gens: [3,4,5], effect: '+20% movs. Normal' },
  { id: 'black-belt', name: 'Cinturón Negro', sprite: 'black-belt', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Lucha' },
  { id: 'charcoal', name: 'Carbón', sprite: 'charcoal', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Fuego' },
  { id: 'mystic-water', name: 'Agua Mística', sprite: 'mystic-water', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Agua' },
  { id: 'magnet', name: 'Imán', sprite: 'magnet', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Eléctrico' },
  { id: 'miracle-seed', name: 'Semilla Milagro', sprite: 'miracle-seed', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Planta' },
  { id: 'never-melt-ice', name: 'Hielo Eterno', sprite: 'never-melt-ice', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Hielo' },
  { id: 'soft-sand', name: 'Arena Fina', sprite: 'soft-sand', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Tierra' },
  { id: 'hard-stone', name: 'Piedra Dura', sprite: 'hard-stone', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Roca' },
  { id: 'sharp-beak', name: 'Pico Afilado', sprite: 'sharp-beak', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Volador' },
  { id: 'poison-barb', name: 'Púa Venenosa', sprite: 'poison-barb', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Veneno' },
  { id: 'spell-tag', name: 'Hechizo', sprite: 'spell-tag', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Fantasma' },
  { id: 'twisted-spoon', name: 'Cuchara Torcida', sprite: 'twisted-spoon', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Psíquico' },
  { id: 'dragon-fang', name: 'Colmillo Dragón', sprite: 'dragon-fang', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Dragón' },
  { id: 'black-glasses', name: 'Gafas de Sol', sprite: 'black-glasses', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Siniestro' },
  { id: 'silver-powder', name: 'Polvo Plata', sprite: 'silver-powder', pocket: 'objetos', gens: [2,3,4,5], effect: '+20% movs. Bicho' },
  { id: 'light-ball', name: 'Bola Luminosa', sprite: 'light-ball', pocket: 'objetos', gens: [2,3,4,5], effect: 'Dobla At./At.Esp. de Pikachu' },
  // Inciensos
  { id: 'sea-incense', name: 'Incienso Marino', sprite: 'sea-incense', pocket: 'objetos', gens: [3,4,5], effect: '+20% Agua; cría Azurill' },
  { id: 'lax-incense', name: 'Incienso Suave', sprite: 'lax-incense', pocket: 'objetos', gens: [3,4,5], effect: 'Baja precisión rival; cría Wynaut' },
  { id: 'odd-incense', name: 'Incienso Raro', sprite: 'odd-incense', pocket: 'objetos', gens: [4,5], effect: '+20% Psíquico; cría Mime Jr.' },
  { id: 'rock-incense', name: 'Incienso Roca', sprite: 'rock-incense', pocket: 'objetos', gens: [4,5], effect: '+20% Roca; cría Bonsly' },
  { id: 'full-incense', name: 'Incienso Lento', sprite: 'full-incense', pocket: 'objetos', gens: [4,5], effect: 'Ataca último; cría Munchlax' },
  { id: 'wave-incense', name: 'Incienso Ola', sprite: 'wave-incense', pocket: 'objetos', gens: [4,5], effect: '+20% Agua; cría Mantyke' },
  { id: 'rose-incense', name: 'Incienso Floral', sprite: 'rose-incense', pocket: 'objetos', gens: [4,5], effect: '+20% Planta; cría Budew' },
  { id: 'luck-incense', name: 'Incienso Suerte', sprite: 'luck-incense', pocket: 'objetos', gens: [4,5], effect: 'Dobla dinero; cría Happiny' },
  { id: 'pure-incense', name: 'Incienso Puro', sprite: 'pure-incense', pocket: 'objetos', gens: [4,5], effect: 'Menos salvajes; cría Chingling' },
  // Power items (EV)
  { id: 'power-weight', name: 'Pesa Recia', sprite: 'power-weight', pocket: 'objetos', gens: [4,5], effect: '+4 EV PS al combatir' },
  { id: 'power-bracer', name: 'Brazal Recio', sprite: 'power-bracer', pocket: 'objetos', gens: [4,5], effect: '+4 EV Ataque al combatir' },
  { id: 'power-belt', name: 'Cinto Recio', sprite: 'power-belt', pocket: 'objetos', gens: [4,5], effect: '+4 EV Defensa al combatir' },
  { id: 'power-lens', name: 'Lente Recia', sprite: 'power-lens', pocket: 'objetos', gens: [4,5], effect: '+4 EV At. Esp. al combatir' },
  { id: 'power-band', name: 'Banda Recia', sprite: 'power-band', pocket: 'objetos', gens: [4,5], effect: '+4 EV Def. Esp. al combatir' },
  { id: 'power-anklet', name: 'Franja Recia', sprite: 'power-anklet', pocket: 'objetos', gens: [4,5], effect: '+4 EV Velocidad al combatir' },
  // Placas de Arceus
  { id: 'flame-plate', name: 'Tabla Llama', sprite: 'flame-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Fuego / Arceus Fuego' },
  { id: 'splash-plate', name: 'Tabla Linfa', sprite: 'splash-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Agua / Arceus Agua' },
  { id: 'zap-plate', name: 'Tabla Trueno', sprite: 'zap-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Eléctrico / Arceus Eléc.' },
  { id: 'meadow-plate', name: 'Tabla Pradera', sprite: 'meadow-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Planta / Arceus Planta' },
  { id: 'icicle-plate', name: 'Tabla Helada', sprite: 'icicle-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Hielo / Arceus Hielo' },
  { id: 'fist-plate', name: 'Tabla Puño', sprite: 'fist-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Lucha / Arceus Lucha' },
  { id: 'toxic-plate', name: 'Tabla Tóxica', sprite: 'toxic-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Veneno / Arceus Veneno' },
  { id: 'earth-plate', name: 'Tabla Terrax', sprite: 'earth-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Tierra / Arceus Tierra' },
  { id: 'sky-plate', name: 'Tabla Cielo', sprite: 'sky-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Volador / Arceus Volador' },
  { id: 'mind-plate', name: 'Tabla Mental', sprite: 'mind-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Psíquico / Arceus Psíq.' },
  { id: 'insect-plate', name: 'Tabla Bicho', sprite: 'insect-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Bicho / Arceus Bicho' },
  { id: 'stone-plate', name: 'Tabla Pétrea', sprite: 'stone-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Roca / Arceus Roca' },
  { id: 'spooky-plate', name: 'Tabla Terror', sprite: 'spooky-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Fantasma / Arceus Fant.' },
  { id: 'draco-plate', name: 'Tabla Draco', sprite: 'draco-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Dragón / Arceus Dragón' },
  { id: 'dread-plate', name: 'Tabla Oscura', sprite: 'dread-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Siniestro / Arceus Sin.' },
  { id: 'iron-plate', name: 'Tabla Férrea', sprite: 'iron-plate', pocket: 'objetos', gens: [4,5], effect: '+20% Acero / Arceus Acero' },
  // Orbes legendarios
  { id: 'adamant-orb', name: 'Diamansfera', sprite: 'adamant-orb', pocket: 'objetos', gens: [4,5], effect: '+20% Dragón/Acero de Dialga' },
  { id: 'lustrous-orb', name: 'Lustresfera', sprite: 'lustrous-orb', pocket: 'objetos', gens: [4,5], effect: '+20% Dragón/Agua de Palkia' },
  { id: 'griseous-orb', name: 'Griseosfera', sprite: 'griseous-orb', pocket: 'objetos', gens: [4,5], effect: 'Forma Origen de Giratina' },
  // Drives de Genesect (Gen 5)
  { id: 'douse-drive', name: 'HidroROM', sprite: 'douse-drive', pocket: 'objetos', gens: [5], effect: 'Tecno Shock → tipo Agua' },
  { id: 'shock-drive', name: 'FulgoROM', sprite: 'shock-drive', pocket: 'objetos', gens: [5], effect: 'Tecno Shock → tipo Eléctrico' },
  { id: 'burn-drive', name: 'PiroROM', sprite: 'burn-drive', pocket: 'objetos', gens: [5], effect: 'Tecno Shock → tipo Fuego' },
  { id: 'chill-drive', name: 'CrioROM', sprite: 'chill-drive', pocket: 'objetos', gens: [5], effect: 'Tecno Shock → tipo Hielo' },
];
