// ===== CATÁLOGO COMPLETO DE OBJETOS (Gen 1-5) - Parte 1: Medicina + Balls =====

export const MEDICINA_ITEMS = [
  { id: 'potion', name: 'Poción', sprite: 'potion', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura 20 PS' },
  { id: 'super-potion', name: 'Superpoción', sprite: 'super-potion', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura 50 PS' },
  { id: 'hyper-potion', name: 'Hiperpoción', sprite: 'hyper-potion', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura 200 PS' },
  { id: 'max-potion', name: 'Poción Máxima', sprite: 'max-potion', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura todos los PS' },
  { id: 'full-restore', name: 'Restaurar Todo', sprite: 'full-restore', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura PS y estado' },
  { id: 'revive', name: 'Revivir', sprite: 'revive', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Revive con 50% PS' },
  { id: 'max-revive', name: 'Revivir Máximo', sprite: 'max-revive', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Revive con todos los PS' },
  { id: 'antidote', name: 'Antídoto', sprite: 'antidote', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Cura envenenamiento' },
  { id: 'paralyze-heal', name: 'Antiparalizador', sprite: 'paralyze-heal', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Cura parálisis' },
  { id: 'burn-heal', name: 'Antiquemar', sprite: 'burn-heal', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Cura quemaduras' },
  { id: 'ice-heal', name: 'Antihielo', sprite: 'ice-heal', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Cura congelación' },
  { id: 'awakening', name: 'Despertar', sprite: 'awakening', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Despierta al Pokémon' },
  { id: 'full-heal', name: 'Cura Total', sprite: 'full-heal', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Cura cualquier estado' },
  { id: 'fresh-water', name: 'Agua Fresca', sprite: 'fresh-water', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura 50 PS' },
  { id: 'soda-pop', name: 'Refresco', sprite: 'soda-pop', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura 60 PS' },
  { id: 'lemonade', name: 'Limonada', sprite: 'lemonade', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura 80 PS' },
  { id: 'moomoo-milk', name: 'Leche Mu-Mu', sprite: 'moomoo-milk', pocket: 'medicina', gens: [2,3,4,5], effect: 'Restaura 100 PS' },
  { id: 'berry-juice', name: 'Zumo de Baya', sprite: 'berry-juice', pocket: 'medicina', gens: [2,3,4,5], effect: 'Restaura 20 PS' },
  { id: 'sacred-ash', name: 'Ceniza Sagrada', sprite: 'sacred-ash', pocket: 'medicina', gens: [2,3,4,5], effect: 'Revive a todo el equipo' },
  { id: 'energy-powder', name: 'Polvo Energía', sprite: 'energy-powder', pocket: 'medicina', gens: [2,3,4,5], effect: 'Restaura 50 PS (amargo)' },
  { id: 'energy-root', name: 'Raíz Energía', sprite: 'energy-root', pocket: 'medicina', gens: [2,3,4,5], effect: 'Restaura 200 PS (amargo)' },
  { id: 'heal-powder', name: 'Polvo Curación', sprite: 'heal-powder', pocket: 'medicina', gens: [2,3,4,5], effect: 'Cura estado (amargo)' },
  { id: 'revival-herb', name: 'Hierba Revivir', sprite: 'revival-herb', pocket: 'medicina', gens: [2,3,4,5], effect: 'Revive (amargo)' },
  { id: 'lava-cookie', name: 'Galleta Lava', sprite: 'lava-cookie', pocket: 'medicina', gens: [3,4,5], effect: 'Cura cualquier estado' },
  { id: 'old-gateau', name: 'Viejo Pastel', sprite: 'old-gateau', pocket: 'medicina', gens: [4,5], effect: 'Cura cualquier estado' },
  { id: 'rage-candy-bar', name: 'Barra Furia', sprite: 'rage-candy-bar', pocket: 'medicina', gens: [2,4,5], effect: 'Cura cualquier estado' },
  { id: 'sweet-heart', name: 'Dulce Corazón', sprite: 'sweet-heart', pocket: 'medicina', gens: [5], effect: 'Restaura 20 PS' },
  { id: 'casteliacone', name: 'Cono Porcelana', sprite: 'casteliacone', pocket: 'medicina', gens: [5], effect: 'Cura cualquier estado' },
  { id: 'rare-candy', name: 'Caramelo Raro', sprite: 'rare-candy', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Sube 1 nivel' },
  { id: 'ether', name: 'Éter', sprite: 'ether', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura 10 PP' },
  { id: 'max-ether', name: 'Éter Máximo', sprite: 'max-ether', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura todos los PP de un mov.' },
  { id: 'elixir', name: 'Elixir', sprite: 'elixir', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura 10 PP a todos' },
  { id: 'max-elixir', name: 'Elixir Máximo', sprite: 'max-elixir', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'Restaura todos los PP' },
];

export const POKEBALL_ITEMS = [
  { id: 'poke-ball', name: 'Poké Ball', sprite: 'poke-ball', pocket: 'pokeballs', gens: [1,2,3,4,5], effect: 'Tasa de captura x1' },
  { id: 'great-ball', name: 'Superball', sprite: 'great-ball', pocket: 'pokeballs', gens: [1,2,3,4,5], effect: 'Tasa de captura x1.5' },
  { id: 'ultra-ball', name: 'Ultraball', sprite: 'ultra-ball', pocket: 'pokeballs', gens: [1,2,3,4,5], effect: 'Tasa de captura x2' },
  { id: 'master-ball', name: 'Master Ball', sprite: 'master-ball', pocket: 'pokeballs', gens: [1,2,3,4,5], effect: 'Captura 100% segura' },
  { id: 'safari-ball', name: 'Safari Ball', sprite: 'safari-ball', pocket: 'pokeballs', gens: [1,2,3,4], effect: 'Solo Zona Safari' },
  { id: 'net-ball', name: 'Malla Ball', sprite: 'net-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'Mejor con Agua/Bicho' },
  { id: 'dive-ball', name: 'Buceo Ball', sprite: 'dive-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'Mejor bajo el agua' },
  { id: 'nest-ball', name: 'Nido Ball', sprite: 'nest-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'Mejor con Pokémon débiles' },
  { id: 'repeat-ball', name: 'Acopio Ball', sprite: 'repeat-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'Mejor si ya capturaste esa especie' },
  { id: 'timer-ball', name: 'Turno Ball', sprite: 'timer-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'Mejor tras varios turnos' },
  { id: 'luxury-ball', name: 'Lujo Ball', sprite: 'luxury-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'Aumenta felicidad' },
  { id: 'premier-ball', name: 'Honor Ball', sprite: 'premier-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'Edición especial' },
  { id: 'dusk-ball', name: 'Ocaso Ball', sprite: 'dusk-ball', pocket: 'pokeballs', gens: [4,5], effect: 'Mejor de noche/cuevas' },
  { id: 'heal-ball', name: 'Sana Ball', sprite: 'heal-ball', pocket: 'pokeballs', gens: [4,5], effect: 'Cura al Pokémon capturado' },
  { id: 'quick-ball', name: 'Veloz Ball', sprite: 'quick-ball', pocket: 'pokeballs', gens: [4,5], effect: 'Mejor en el primer turno' },
  { id: 'cherish-ball', name: 'Gloria Ball', sprite: 'cherish-ball', pocket: 'pokeballs', gens: [4,5], effect: 'Para Pokémon de evento' },
  { id: 'heavy-ball', name: 'Peso Ball', sprite: 'heavy-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'Mejor con Pokémon pesados' },
  { id: 'love-ball', name: 'Amor Ball', sprite: 'love-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'Mejor con sexo opuesto' },
  { id: 'friend-ball', name: 'Amigo Ball', sprite: 'friend-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'Más felicidad inicial' },
  { id: 'lure-ball', name: 'Cebo Ball', sprite: 'lure-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'Mejor con Pokémon pescados' },
  { id: 'level-ball', name: 'Nivel Ball', sprite: 'level-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'Mejor si tu nivel es mayor' },
  { id: 'fast-ball', name: 'Rapid Ball', sprite: 'fast-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'Mejor con Pokémon rápidos' },
  { id: 'moon-ball', name: 'Luna Ball', sprite: 'moon-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'Mejor con evol. Piedra Lunar' },
  { id: 'sport-ball', name: 'Competi Ball', sprite: 'sport-ball', pocket: 'pokeballs', gens: [2,4], effect: 'Concurso Atrapa Bichos' },
  { id: 'park-ball', name: 'Parque Ball', sprite: 'park-ball', pocket: 'pokeballs', gens: [4], effect: 'Para Parque Compi' },
  { id: 'dream-ball', name: 'Ensueño Ball', sprite: 'dream-ball', pocket: 'pokeballs', gens: [5], effect: 'Bosque Blanco/Isla de los Sueños' },
];
