// ===== CATÁLOGO COMPLETO - Parte 3: Combate, Bayas, Objetos Clave, Gemas =====

export const COMBATE_ITEMS = [
  { id: 'x-attack', name: 'Ataque X', sprite: 'x-attack', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: '+1 nivel de Ataque' },
  { id: 'x-defense', name: 'Defensa X', sprite: 'x-defense', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: '+1 nivel de Defensa' },
  { id: 'x-speed', name: 'Velocidad X', sprite: 'x-speed', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: '+1 nivel de Velocidad' },
  { id: 'x-accuracy', name: 'Precisión X', sprite: 'x-accuracy', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: '+1 nivel de Precisión' },
  { id: 'x-sp-atk', name: 'At. Especial X', sprite: 'x-sp-atk', pocket: 'objetos_combate', gens: [3,4,5], effect: '+1 nivel At. Especial' },
  { id: 'x-sp-def', name: 'Def. Especial X', sprite: 'x-sp-def', pocket: 'objetos_combate', gens: [3,4,5], effect: '+1 nivel Def. Especial' },
  { id: 'guard-spec', name: 'Guardia Especial', sprite: 'guard-spec', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: 'Protege de cambios de stats' },
  { id: 'dire-hit', name: 'Golpe Crítico', sprite: 'dire-hit', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: 'Aumenta ratio de crítico' },
  { id: 'fluffy-tail', name: 'Cola Pokémon', sprite: 'fluffy-tail', pocket: 'objetos_combate', gens: [3,4,5], effect: 'Permite huir de salvajes' },
  { id: 'poke-doll', name: 'Poké Muñeco', sprite: 'poke-doll', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: 'Permite huir de salvajes' },
  { id: 'poke-toy', name: 'Poké Juguete', sprite: 'poke-toy', pocket: 'objetos_combate', gens: [5], effect: 'Permite huir de salvajes' },
];

export const BAYA_ITEMS = [
  // Bayas curativas
  { id: 'oran-berry', name: 'Baya Aranja', sprite: 'oran-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Restaura 10 PS' },
  { id: 'sitrus-berry', name: 'Baya Zidra', sprite: 'sitrus-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Restaura 25% PS' },
  { id: 'lum-berry', name: 'Baya Ziuela', sprite: 'lum-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Cura cualquier estado' },
  { id: 'leppa-berry', name: 'Baya Zanama', sprite: 'leppa-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Restaura 10 PP' },
  { id: 'cheri-berry', name: 'Baya Zreza', sprite: 'cheri-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Cura parálisis' },
  { id: 'chesto-berry', name: 'Baya Atania', sprite: 'chesto-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Despierta al Pokémon' },
  { id: 'pecha-berry', name: 'Baya Meloc', sprite: 'pecha-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Cura envenenamiento' },
  { id: 'rawst-berry', name: 'Baya Safre', sprite: 'rawst-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Cura quemaduras' },
  { id: 'aspear-berry', name: 'Baya Perasi', sprite: 'aspear-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Cura congelación' },
  { id: 'persim-berry', name: 'Baya Caquic', sprite: 'persim-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Cura confusión' },
  // Bayas de sabor (restauran PS con confusión si no gusta)
  { id: 'figy-berry', name: 'Baya Higog', sprite: 'figy-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Restaura PS (picante)' },
  { id: 'wiki-berry', name: 'Baya Wiki', sprite: 'wiki-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Restaura PS (seco)' },
  { id: 'mago-berry', name: 'Baya Ango', sprite: 'mago-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Restaura PS (dulce)' },
  { id: 'aguav-berry', name: 'Baya Guaya', sprite: 'aguav-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Restaura PS (amargo)' },
  { id: 'iapapa-berry', name: 'Baya Papaya', sprite: 'iapapa-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Restaura PS (ácido)' },
  // Bayas para Pokécubos/Pokélitos
  { id: 'razz-berry', name: 'Baya Frambu', sprite: 'razz-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Para Pokécubos/Pokélitos' },
  { id: 'bluk-berry', name: 'Baya Oram', sprite: 'bluk-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Para Pokécubos/Pokélitos' },
  { id: 'nanab-berry', name: 'Baya Platan', sprite: 'nanab-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Para Pokécubos/Pokélitos' },
  { id: 'wepear-berry', name: 'Baya Peragu', sprite: 'wepear-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Para Pokécubos/Pokélitos' },
  { id: 'pinap-berry', name: 'Baya Pinia', sprite: 'pinap-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Para Pokécubos/Pokélitos' },
  // Bayas reductoras de EV
  { id: 'pomeg-berry', name: 'Baya Grana', sprite: 'pomeg-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Baja EV de PS, sube felicidad' },
  { id: 'kelpsy-berry', name: 'Baya Alga', sprite: 'kelpsy-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Baja EV de Ataque' },
  { id: 'qualot-berry', name: 'Baya Ispero', sprite: 'qualot-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Baja EV de Defensa' },
  { id: 'hondew-berry', name: 'Baya Meluce', sprite: 'hondew-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Baja EV de At. Especial' },
  { id: 'grepa-berry', name: 'Baya Uvav', sprite: 'grepa-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Baja EV de Def. Especial' },
  { id: 'tamato-berry', name: 'Baya Tamate', sprite: 'tamato-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Baja EV de Velocidad' },
  // Bayas para Pokécubos raros
  { id: 'cornn-berry', name: 'Baya Maíz', sprite: 'cornn-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Pokécubos/Pokélitos raros' },
  { id: 'magost-berry', name: 'Baya Mangost', sprite: 'magost-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Pokécubos/Pokélitos raros' },
  { id: 'rabuta-berry', name: 'Baya Rautan', sprite: 'rabuta-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Pokécubos/Pokélitos raros' },
  { id: 'nomel-berry', name: 'Baya Monli', sprite: 'nomel-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Pokécubos/Pokélitos raros' },
  { id: 'spelon-berry', name: 'Baya Wikano', sprite: 'spelon-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Pokécubos/Pokélitos raros' },
  { id: 'pamtre-berry', name: 'Baya Plama', sprite: 'pamtre-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Pokécubos/Pokélitos raros' },
  { id: 'watmel-berry', name: 'Baya Sambia', sprite: 'watmel-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Pokécubos/Pokélitos raros' },
  { id: 'durin-berry', name: 'Baya Durian', sprite: 'durin-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Pokécubos/Pokélitos raros' },
  { id: 'belue-berry', name: 'Baya Aráz', sprite: 'belue-berry', pocket: 'bayas', gens: [3,4,5], effect: 'Pokécubos/Pokélitos raros' },
  // Bayas reductoras de daño por tipo (Gen 4)
  { id: 'occa-berry', name: 'Baya Ksjud', sprite: 'occa-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Fuego' },
  { id: 'passho-berry', name: 'Baya Pasio', sprite: 'passho-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Agua' },
  { id: 'wacan-berry', name: 'Baya Gualot', sprite: 'wacan-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Eléctrico' },
  { id: 'rindo-berry', name: 'Baya Tamar', sprite: 'rindo-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Planta' },
  { id: 'yache-berry', name: 'Baya Yecas', sprite: 'yache-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Hielo' },
  { id: 'chople-berry', name: 'Baya Choidre', sprite: 'chople-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Lucha' },
  { id: 'kebia-berry', name: 'Baya Kebia', sprite: 'kebia-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Veneno' },
  { id: 'shuca-berry', name: 'Baya Acardo', sprite: 'shuca-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Tierra' },
  { id: 'coba-berry', name: 'Baya Kouba', sprite: 'coba-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Volador' },
  { id: 'payapa-berry', name: 'Baya Payapa', sprite: 'payapa-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Psíquico' },
  { id: 'tanga-berry', name: 'Baya Tanga', sprite: 'tanga-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Bicho' },
  { id: 'charti-berry', name: 'Baya Alchar', sprite: 'charti-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Roca' },
  { id: 'kasib-berry', name: 'Baya Bakis', sprite: 'kasib-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Fantasma' },
  { id: 'haban-berry', name: 'Baya Anjiro', sprite: 'haban-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Dragón' },
  { id: 'colbur-berry', name: 'Baya Dsjit', sprite: 'colbur-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Siniestro' },
  { id: 'babiri-berry', name: 'Baya Jaboca', sprite: 'babiri-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño superefectivo Acero' },
  { id: 'chilan-berry', name: 'Baya Chilan', sprite: 'chilan-berry', pocket: 'bayas', gens: [4,5], effect: 'Reduce daño de tipo Normal' },
  // Bayas competitivas (boost con PS bajos)
  { id: 'liechi-berry', name: 'Baya Lichi', sprite: 'liechi-berry', pocket: 'bayas', gens: [3,4,5], effect: '+Ataque con PS bajos' },
  { id: 'ganlon-berry', name: 'Baya Gonlan', sprite: 'ganlon-berry', pocket: 'bayas', gens: [3,4,5], effect: '+Defensa con PS bajos' },
  { id: 'salac-berry', name: 'Baya Aslac', sprite: 'salac-berry', pocket: 'bayas', gens: [3,4,5], effect: '+Velocidad con PS bajos' },
  { id: 'petaya-berry', name: 'Baya Pitaya', sprite: 'petaya-berry', pocket: 'bayas', gens: [3,4,5], effect: '+At. Esp. con PS bajos' },
  { id: 'apicot-berry', name: 'Baya Aricoc', sprite: 'apicot-berry', pocket: 'bayas', gens: [3,4,5], effect: '+Def. Esp. con PS bajos' },
  { id: 'lansat-berry', name: 'Baya Zonlan', sprite: 'lansat-berry', pocket: 'bayas', gens: [3,4,5], effect: '+Crítico con PS bajos' },
  { id: 'starf-berry', name: 'Baya Arabol', sprite: 'starf-berry', pocket: 'bayas', gens: [3,4,5], effect: '+2 stat aleatorio con PS bajos' },
  { id: 'enigma-berry', name: 'Baya Enigma', sprite: 'enigma-berry', pocket: 'bayas', gens: [4,5], effect: 'Restaura PS si golpe superefectivo' },
  { id: 'micle-berry', name: 'Baya Lagro', sprite: 'micle-berry', pocket: 'bayas', gens: [4,5], effect: '+Precisión con PS bajos' },
  { id: 'custap-berry', name: 'Baya Chiri', sprite: 'custap-berry', pocket: 'bayas', gens: [4,5], effect: 'Prioridad +1 con PS bajos' },
  { id: 'jaboca-berry', name: 'Baya Jaboca', sprite: 'jaboca-berry', pocket: 'bayas', gens: [4,5], effect: 'Daña al rival si ataque físico' },
  { id: 'rowap-berry', name: 'Baya Rowan', sprite: 'rowap-berry', pocket: 'bayas', gens: [4,5], effect: 'Daña al rival si ataque especial' },
];

export const GEMA_ITEMS = [
  { id: 'fire-gem', name: 'Gema Fuego', sprite: 'fire-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Fuego (1 uso)' },
  { id: 'water-gem', name: 'Gema Agua', sprite: 'water-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Agua (1 uso)' },
  { id: 'electric-gem', name: 'Gema Eléctrica', sprite: 'electric-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Eléctrico' },
  { id: 'grass-gem', name: 'Gema Planta', sprite: 'grass-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Planta' },
  { id: 'ice-gem', name: 'Gema Hielo', sprite: 'ice-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Hielo' },
  { id: 'fighting-gem', name: 'Gema Lucha', sprite: 'fighting-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Lucha' },
  { id: 'poison-gem', name: 'Gema Veneno', sprite: 'poison-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Veneno' },
  { id: 'ground-gem', name: 'Gema Tierra', sprite: 'ground-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Tierra' },
  { id: 'flying-gem', name: 'Gema Voladora', sprite: 'flying-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Volador' },
  { id: 'psychic-gem', name: 'Gema Psíquica', sprite: 'psychic-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Psíquico' },
  { id: 'bug-gem', name: 'Gema Bicho', sprite: 'bug-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Bicho' },
  { id: 'rock-gem', name: 'Gema Roca', sprite: 'rock-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Roca' },
  { id: 'ghost-gem', name: 'Gema Fantasma', sprite: 'ghost-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Fantasma' },
  { id: 'dragon-gem', name: 'Gema Dragón', sprite: 'dragon-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Dragón' },
  { id: 'dark-gem', name: 'Gema Siniestra', sprite: 'dark-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Siniestro' },
  { id: 'steel-gem', name: 'Gema Acero', sprite: 'steel-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Acero' },
  { id: 'normal-gem', name: 'Gema Normal', sprite: 'normal-gem', pocket: 'objetos', gens: [5], effect: '+30% primer mov. Normal' },
];

export const CLAVE_ITEMS = [
  { id: 'bicycle', name: 'Bicicleta', sprite: 'bicycle', pocket: 'objetos_clave', gens: [1,2,3,4,5], effect: 'Viaja más rápido' },
  { id: 'old-rod', name: 'Caña Vieja', sprite: 'old-rod', pocket: 'objetos_clave', gens: [1,2,3,4,5], effect: 'Pesca Pokémon básicos' },
  { id: 'good-rod', name: 'Caña Buena', sprite: 'good-rod', pocket: 'objetos_clave', gens: [1,2,3,4,5], effect: 'Pesca Pokémon intermedios' },
  { id: 'super-rod', name: 'Supercaña', sprite: 'super-rod', pocket: 'objetos_clave', gens: [1,2,3,4,5], effect: 'Pesca Pokémon raros' },
  { id: 'town-map', name: 'Mapa', sprite: 'town-map', pocket: 'objetos_clave', gens: [1,2,3,4,5], effect: 'Muestra la región' },
  { id: 'vs-seeker', name: 'Buscapelea', sprite: 'vs-seeker', pocket: 'objetos_clave', gens: [1,3,4], effect: 'Rebusca combates' },
  { id: 'coin-case', name: 'Monedero', sprite: 'coin-case', pocket: 'objetos_clave', gens: [1,2,3,4], effect: 'Guarda fichas del Casino' },
  { id: 'dowsing-machine', name: 'Zahorí', sprite: 'dowsing-machine', pocket: 'objetos_clave', gens: [4,5], effect: 'Encuentra objetos ocultos' },
  { id: 'ss-ticket', name: 'Billete S.S.', sprite: 'ss-ticket', pocket: 'objetos_clave', gens: [1,2], effect: 'Acceso al S.S. Anne/Aqua' },
  { id: 'poke-flute', name: 'Poké Flauta', sprite: 'poke-flute', pocket: 'objetos_clave', gens: [1], effect: 'Despierta a Snorlax' },
  { id: 'silph-scope', name: 'Scope Silph', sprite: 'silph-scope', pocket: 'objetos_clave', gens: [1], effect: 'Revela fantasmas' },
  { id: 'poke-radar', name: 'Poké Radar', sprite: 'poke-radar', pocket: 'objetos_clave', gens: [4], effect: 'Busca Pokémon en la hierba' },
  { id: 'explorer-kit', name: 'Kit Explorador', sprite: 'explorer-kit', pocket: 'objetos_clave', gens: [4], effect: 'Acceso al Subterráneo' },
  { id: 'sprayduck', name: 'Regadera', sprite: 'sprayduck', pocket: 'objetos_clave', gens: [4], effect: 'Riega las bayas' },
  { id: 'squirt-bottle', name: 'Botella Squirt', sprite: 'squirt-bottle', pocket: 'objetos_clave', gens: [2], effect: 'Riega árboles / Sudowoodo' },
  { id: 'apricorn-box', name: 'Caja Bonguri', sprite: 'apricorn-box', pocket: 'objetos_clave', gens: [2], effect: 'Guarda Bonguri' },
  { id: 'wailmer-pail', name: 'Regadera Wailmer', sprite: 'wailmer-pail', pocket: 'objetos_clave', gens: [3], effect: 'Riega las bayas' },
  { id: 'mach-bike', name: 'Bici Carreras', sprite: 'mach-bike', pocket: 'objetos_clave', gens: [3], effect: 'Bicicleta rápida' },
  { id: 'acro-bike', name: 'Bici Acrobática', sprite: 'acro-bike', pocket: 'objetos_clave', gens: [3], effect: 'Bicicleta de trucos' },
  { id: 'go-goggles', name: 'Gafas Protectoras', sprite: 'go-goggles', pocket: 'objetos_clave', gens: [3], effect: 'Protege del desierto' },
  { id: 'devon-scope', name: 'Devon Scope', sprite: 'devon-scope', pocket: 'objetos_clave', gens: [3], effect: 'Revela Pokémon invisibles' },
  { id: 'vs-recorder', name: 'Grabadora VS', sprite: 'vs-recorder', pocket: 'objetos_clave', gens: [4,5], effect: 'Graba combates' },
  { id: 'pal-pad', name: 'Libreta Amigos', sprite: 'pal-pad', pocket: 'objetos_clave', gens: [4], effect: 'Registra Códigos Amigo' },
  { id: 'gracidea', name: 'Gracídea', sprite: 'gracidea', pocket: 'objetos_clave', gens: [4,5], effect: 'Forma Cielo de Shaymin' },
  { id: 'prop-case', name: 'Estuche Props', sprite: 'prop-case', pocket: 'objetos_clave', gens: [5], effect: 'Props del Musical Pokémon' },
  { id: 'xtransceiver', name: 'Videomisor', sprite: 'xtransceiver', pocket: 'objetos_clave', gens: [5], effect: 'Videollamadas' },
  { id: 'medal-box', name: 'Caja Medallas', sprite: 'medal-box', pocket: 'objetos_clave', gens: [5], effect: 'Guarda medallas (B2W2)' },
  { id: 'dna-splicers', name: 'Punta ADN', sprite: 'dna-splicers', pocket: 'objetos_clave', gens: [5], effect: 'Fusiona Kyurem (B2W2)' },
  { id: 'reveal-glass', name: 'Espejo Veraz', sprite: 'reveal-glass', pocket: 'objetos_clave', gens: [5], effect: 'Forma de genios (B2W2)' },
];
