// ===== CATÁLOGO COMPLETO DE OBJETOS (Gen 1-5) - Parte 1: Medicina + Balls =====

export const MEDICINA_ITEMS = [
  { id: 'potion', name: 'Poción', sprite: 'potion', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.potion.effect' },
  { id: 'super-potion', name: 'Superpoción', sprite: 'super-potion', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.super-potion.effect' },
  { id: 'hyper-potion', name: 'Hiperpoción', sprite: 'hyper-potion', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.hyper-potion.effect' },
  { id: 'max-potion', name: 'Poción Máxima', sprite: 'max-potion', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.max-potion.effect' },
  { id: 'full-restore', name: 'Restaurar Todo', sprite: 'full-restore', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.full-restore.effect' },
  { id: 'revive', name: 'Revivir', sprite: 'revive', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.revive.effect' },
  { id: 'max-revive', name: 'Revivir Máximo', sprite: 'max-revive', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.max-revive.effect' },
  { id: 'antidote', name: 'Antídoto', sprite: 'antidote', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.antidote.effect' },
  { id: 'paralyze-heal', name: 'Antiparalizador', sprite: 'paralyze-heal', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.paralyze-heal.effect' },
  { id: 'burn-heal', name: 'Antiquemar', sprite: 'burn-heal', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.burn-heal.effect' },
  { id: 'ice-heal', name: 'Antihielo', sprite: 'ice-heal', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.ice-heal.effect' },
  { id: 'awakening', name: 'Despertar', sprite: 'awakening', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.awakening.effect' },
  { id: 'full-heal', name: 'Cura Total', sprite: 'full-heal', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.full-heal.effect' },
  { id: 'fresh-water', name: 'Agua Fresca', sprite: 'fresh-water', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.fresh-water.effect' },
  { id: 'soda-pop', name: 'Refresco', sprite: 'soda-pop', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.soda-pop.effect' },
  { id: 'lemonade', name: 'Limonada', sprite: 'lemonade', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.lemonade.effect' },
  { id: 'moomoo-milk', name: 'Leche Mu-Mu', sprite: 'moomoo-milk', pocket: 'medicina', gens: [2,3,4,5], effect: 'items.moomoo-milk.effect' },
  { id: 'berry-juice', name: 'Zumo de Baya', sprite: 'berry-juice', pocket: 'medicina', gens: [2,3,4,5], effect: 'items.berry-juice.effect' },
  { id: 'sacred-ash', name: 'Ceniza Sagrada', sprite: 'sacred-ash', pocket: 'medicina', gens: [2,3,4,5], effect: 'items.sacred-ash.effect' },
  { id: 'energy-powder', name: 'Polvo Energía', sprite: 'energy-powder', pocket: 'medicina', gens: [2,3,4,5], effect: 'items.energy-powder.effect' },
  { id: 'energy-root', name: 'Raíz Energía', sprite: 'energy-root', pocket: 'medicina', gens: [2,3,4,5], effect: 'items.energy-root.effect' },
  { id: 'heal-powder', name: 'Polvo Curación', sprite: 'heal-powder', pocket: 'medicina', gens: [2,3,4,5], effect: 'items.heal-powder.effect' },
  { id: 'revival-herb', name: 'Hierba Revivir', sprite: 'revival-herb', pocket: 'medicina', gens: [2,3,4,5], effect: 'items.revival-herb.effect' },
  { id: 'lava-cookie', name: 'Galleta Lava', sprite: 'lava-cookie', pocket: 'medicina', gens: [3,4,5], effect: 'items.lava-cookie.effect' },
  { id: 'old-gateau', name: 'Viejo Pastel', sprite: 'old-gateau', pocket: 'medicina', gens: [4,5], effect: 'items.old-gateau.effect' },
  { id: 'rage-candy-bar', name: 'Barra Furia', sprite: 'rage-candy-bar', pocket: 'medicina', gens: [2,4,5], effect: 'items.rage-candy-bar.effect' },
  { id: 'sweet-heart', name: 'Dulce Corazón', sprite: 'sweet-heart', pocket: 'medicina', gens: [5], effect: 'items.sweet-heart.effect' },
  { id: 'casteliacone', name: 'Cono Porcelana', sprite: 'casteliacone', pocket: 'medicina', gens: [5], effect: 'items.casteliacone.effect' },
  { id: 'rare-candy', name: 'Caramelo Raro', sprite: 'rare-candy', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.rare-candy.effect' },
  { id: 'ether', name: 'Éter', sprite: 'ether', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.ether.effect' },
  { id: 'max-ether', name: 'Éter Máximo', sprite: 'max-ether', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.max-ether.effect' },
  { id: 'elixir', name: 'Elixir', sprite: 'elixir', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.elixir.effect' },
  { id: 'max-elixir', name: 'Elixir Máximo', sprite: 'max-elixir', pocket: 'medicina', gens: [1,2,3,4,5], effect: 'items.max-elixir.effect' },
];

export const POKEBALL_ITEMS = [
  { id: 'poke-ball', name: 'Poké Ball', sprite: 'poke-ball', pocket: 'pokeballs', gens: [1,2,3,4,5], effect: 'items.poke-ball.effect' },
  { id: 'great-ball', name: 'Superball', sprite: 'great-ball', pocket: 'pokeballs', gens: [1,2,3,4,5], effect: 'items.great-ball.effect' },
  { id: 'ultra-ball', name: 'Ultraball', sprite: 'ultra-ball', pocket: 'pokeballs', gens: [1,2,3,4,5], effect: 'items.ultra-ball.effect' },
  { id: 'master-ball', name: 'Master Ball', sprite: 'master-ball', pocket: 'pokeballs', gens: [1,2,3,4,5], effect: 'items.master-ball.effect' },
  { id: 'safari-ball', name: 'Safari Ball', sprite: 'safari-ball', pocket: 'pokeballs', gens: [1,2,3,4], effect: 'items.safari-ball.effect' },
  { id: 'net-ball', name: 'Malla Ball', sprite: 'net-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'items.net-ball.effect' },
  { id: 'dive-ball', name: 'Buceo Ball', sprite: 'dive-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'items.dive-ball.effect' },
  { id: 'nest-ball', name: 'Nido Ball', sprite: 'nest-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'items.nest-ball.effect' },
  { id: 'repeat-ball', name: 'Acopio Ball', sprite: 'repeat-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'items.repeat-ball.effect' },
  { id: 'timer-ball', name: 'Turno Ball', sprite: 'timer-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'items.timer-ball.effect' },
  { id: 'luxury-ball', name: 'Lujo Ball', sprite: 'luxury-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'items.luxury-ball.effect' },
  { id: 'premier-ball', name: 'Honor Ball', sprite: 'premier-ball', pocket: 'pokeballs', gens: [3,4,5], effect: 'items.premier-ball.effect' },
  { id: 'dusk-ball', name: 'Ocaso Ball', sprite: 'dusk-ball', pocket: 'pokeballs', gens: [4,5], effect: 'items.dusk-ball.effect' },
  { id: 'heal-ball', name: 'Sana Ball', sprite: 'heal-ball', pocket: 'pokeballs', gens: [4,5], effect: 'items.heal-ball.effect' },
  { id: 'quick-ball', name: 'Veloz Ball', sprite: 'quick-ball', pocket: 'pokeballs', gens: [4,5], effect: 'items.quick-ball.effect' },
  { id: 'cherish-ball', name: 'Gloria Ball', sprite: 'cherish-ball', pocket: 'pokeballs', gens: [4,5], effect: 'items.cherish-ball.effect' },
  { id: 'heavy-ball', name: 'Peso Ball', sprite: 'heavy-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'items.heavy-ball.effect' },
  { id: 'love-ball', name: 'Amor Ball', sprite: 'love-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'items.love-ball.effect' },
  { id: 'friend-ball', name: 'Amigo Ball', sprite: 'friend-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'items.friend-ball.effect' },
  { id: 'lure-ball', name: 'Cebo Ball', sprite: 'lure-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'items.lure-ball.effect' },
  { id: 'level-ball', name: 'Nivel Ball', sprite: 'level-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'items.level-ball.effect' },
  { id: 'fast-ball', name: 'Rapid Ball', sprite: 'fast-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'items.fast-ball.effect' },
  { id: 'moon-ball', name: 'Luna Ball', sprite: 'moon-ball', pocket: 'pokeballs', gens: [2,4,5], effect: 'items.moon-ball.effect' },
  { id: 'sport-ball', name: 'Competi Ball', sprite: 'sport-ball', pocket: 'pokeballs', gens: [2,4], effect: 'items.sport-ball.effect' },
  { id: 'park-ball', name: 'Parque Ball', sprite: 'park-ball', pocket: 'pokeballs', gens: [4], effect: 'items.park-ball.effect' },
  { id: 'dream-ball', name: 'Ensueño Ball', sprite: 'dream-ball', pocket: 'pokeballs', gens: [5], effect: 'items.dream-ball.effect' },
];
