// ===== CATÁLOGO COMPLETO - Parte 3: Combate, Bayas, Objetos Clave, Gemas =====

export const COMBATE_ITEMS = [
  { id: 'x-attack', name: 'Ataque X', sprite: 'x-attack', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: 'items.x-attack.effect' },
  { id: 'x-defense', name: 'Defensa X', sprite: 'x-defense', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: 'items.x-defense.effect' },
  { id: 'x-speed', name: 'Velocidad X', sprite: 'x-speed', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: 'items.x-speed.effect' },
  { id: 'x-accuracy', name: 'Precisión X', sprite: 'x-accuracy', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: 'items.x-accuracy.effect' },
  { id: 'x-sp-atk', name: 'At. Especial X', sprite: 'x-sp-atk', pocket: 'objetos_combate', gens: [3,4,5], effect: 'items.x-sp-atk.effect' },
  { id: 'x-sp-def', name: 'Def. Especial X', sprite: 'x-sp-def', pocket: 'objetos_combate', gens: [3,4,5], effect: 'items.x-sp-def.effect' },
  { id: 'guard-spec', name: 'Guardia Especial', sprite: 'guard-spec', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: 'items.guard-spec.effect' },
  { id: 'dire-hit', name: 'Golpe Crítico', sprite: 'dire-hit', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: 'items.dire-hit.effect' },
  { id: 'fluffy-tail', name: 'Cola Pokémon', sprite: 'fluffy-tail', pocket: 'objetos_combate', gens: [3,4,5], effect: 'items.fluffy-tail.effect' },
  { id: 'poke-doll', name: 'Poké Muñeco', sprite: 'poke-doll', pocket: 'objetos_combate', gens: [1,2,3,4,5], effect: 'items.poke-doll.effect' },
  { id: 'poke-toy', name: 'Poké Juguete', sprite: 'poke-toy', pocket: 'objetos_combate', gens: [5], effect: 'items.poke-toy.effect' },
];

export const BAYA_ITEMS = [
  // Bayas curativas
  { id: 'oran-berry', name: 'Baya Aranja', sprite: 'oran-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.oran-berry.effect' },
  { id: 'sitrus-berry', name: 'Baya Zidra', sprite: 'sitrus-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.sitrus-berry.effect' },
  { id: 'lum-berry', name: 'Baya Ziuela', sprite: 'lum-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.lum-berry.effect' },
  { id: 'leppa-berry', name: 'Baya Zanama', sprite: 'leppa-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.leppa-berry.effect' },
  { id: 'cheri-berry', name: 'Baya Zreza', sprite: 'cheri-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.cheri-berry.effect' },
  { id: 'chesto-berry', name: 'Baya Atania', sprite: 'chesto-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.chesto-berry.effect' },
  { id: 'pecha-berry', name: 'Baya Meloc', sprite: 'pecha-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.pecha-berry.effect' },
  { id: 'rawst-berry', name: 'Baya Safre', sprite: 'rawst-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.rawst-berry.effect' },
  { id: 'aspear-berry', name: 'Baya Perasi', sprite: 'aspear-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.aspear-berry.effect' },
  { id: 'persim-berry', name: 'Baya Caquic', sprite: 'persim-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.persim-berry.effect' },
  // Bayas de sabor (restauran PS con confusión si no gusta)
  { id: 'figy-berry', name: 'Baya Higog', sprite: 'figy-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.figy-berry.effect' },
  { id: 'wiki-berry', name: 'Baya Wiki', sprite: 'wiki-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.wiki-berry.effect' },
  { id: 'mago-berry', name: 'Baya Ango', sprite: 'mago-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.mago-berry.effect' },
  { id: 'aguav-berry', name: 'Baya Guaya', sprite: 'aguav-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.aguav-berry.effect' },
  { id: 'iapapa-berry', name: 'Baya Papaya', sprite: 'iapapa-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.iapapa-berry.effect' },
  // Bayas para Pokécubos/Pokélitos
  { id: 'razz-berry', name: 'Baya Frambu', sprite: 'razz-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.razz-berry.effect' },
  { id: 'bluk-berry', name: 'Baya Oram', sprite: 'bluk-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.bluk-berry.effect' },
  { id: 'nanab-berry', name: 'Baya Platan', sprite: 'nanab-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.nanab-berry.effect' },
  { id: 'wepear-berry', name: 'Baya Peragu', sprite: 'wepear-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.wepear-berry.effect' },
  { id: 'pinap-berry', name: 'Baya Pinia', sprite: 'pinap-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.pinap-berry.effect' },
  // Bayas reductoras de EV
  { id: 'pomeg-berry', name: 'Baya Grana', sprite: 'pomeg-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.pomeg-berry.effect' },
  { id: 'kelpsy-berry', name: 'Baya Alga', sprite: 'kelpsy-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.kelpsy-berry.effect' },
  { id: 'qualot-berry', name: 'Baya Ispero', sprite: 'qualot-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.qualot-berry.effect' },
  { id: 'hondew-berry', name: 'Baya Meluce', sprite: 'hondew-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.hondew-berry.effect' },
  { id: 'grepa-berry', name: 'Baya Uvav', sprite: 'grepa-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.grepa-berry.effect' },
  { id: 'tamato-berry', name: 'Baya Tamate', sprite: 'tamato-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.tamato-berry.effect' },
  // Bayas para Pokécubos raros
  { id: 'cornn-berry', name: 'Baya Maíz', sprite: 'cornn-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.cornn-berry.effect' },
  { id: 'magost-berry', name: 'Baya Mangost', sprite: 'magost-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.magost-berry.effect' },
  { id: 'rabuta-berry', name: 'Baya Rautan', sprite: 'rabuta-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.rabuta-berry.effect' },
  { id: 'nomel-berry', name: 'Baya Monli', sprite: 'nomel-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.nomel-berry.effect' },
  { id: 'spelon-berry', name: 'Baya Wikano', sprite: 'spelon-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.spelon-berry.effect' },
  { id: 'pamtre-berry', name: 'Baya Plama', sprite: 'pamtre-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.pamtre-berry.effect' },
  { id: 'watmel-berry', name: 'Baya Sambia', sprite: 'watmel-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.watmel-berry.effect' },
  { id: 'durin-berry', name: 'Baya Durian', sprite: 'durin-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.durin-berry.effect' },
  { id: 'belue-berry', name: 'Baya Aráz', sprite: 'belue-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.belue-berry.effect' },
  // Bayas reductoras de daño por tipo (Gen 4)
  { id: 'occa-berry', name: 'Baya Ksjud', sprite: 'occa-berry', pocket: 'bayas', gens: [4,5], effect: 'items.occa-berry.effect' },
  { id: 'passho-berry', name: 'Baya Pasio', sprite: 'passho-berry', pocket: 'bayas', gens: [4,5], effect: 'items.passho-berry.effect' },
  { id: 'wacan-berry', name: 'Baya Gualot', sprite: 'wacan-berry', pocket: 'bayas', gens: [4,5], effect: 'items.wacan-berry.effect' },
  { id: 'rindo-berry', name: 'Baya Tamar', sprite: 'rindo-berry', pocket: 'bayas', gens: [4,5], effect: 'items.rindo-berry.effect' },
  { id: 'yache-berry', name: 'Baya Yecas', sprite: 'yache-berry', pocket: 'bayas', gens: [4,5], effect: 'items.yache-berry.effect' },
  { id: 'chople-berry', name: 'Baya Choidre', sprite: 'chople-berry', pocket: 'bayas', gens: [4,5], effect: 'items.chople-berry.effect' },
  { id: 'kebia-berry', name: 'Baya Kebia', sprite: 'kebia-berry', pocket: 'bayas', gens: [4,5], effect: 'items.kebia-berry.effect' },
  { id: 'shuca-berry', name: 'Baya Acardo', sprite: 'shuca-berry', pocket: 'bayas', gens: [4,5], effect: 'items.shuca-berry.effect' },
  { id: 'coba-berry', name: 'Baya Kouba', sprite: 'coba-berry', pocket: 'bayas', gens: [4,5], effect: 'items.coba-berry.effect' },
  { id: 'payapa-berry', name: 'Baya Payapa', sprite: 'payapa-berry', pocket: 'bayas', gens: [4,5], effect: 'items.payapa-berry.effect' },
  { id: 'tanga-berry', name: 'Baya Tanga', sprite: 'tanga-berry', pocket: 'bayas', gens: [4,5], effect: 'items.tanga-berry.effect' },
  { id: 'charti-berry', name: 'Baya Alchar', sprite: 'charti-berry', pocket: 'bayas', gens: [4,5], effect: 'items.charti-berry.effect' },
  { id: 'kasib-berry', name: 'Baya Bakis', sprite: 'kasib-berry', pocket: 'bayas', gens: [4,5], effect: 'items.kasib-berry.effect' },
  { id: 'haban-berry', name: 'Baya Anjiro', sprite: 'haban-berry', pocket: 'bayas', gens: [4,5], effect: 'items.haban-berry.effect' },
  { id: 'colbur-berry', name: 'Baya Dsjit', sprite: 'colbur-berry', pocket: 'bayas', gens: [4,5], effect: 'items.colbur-berry.effect' },
  { id: 'babiri-berry', name: 'Baya Jaboca', sprite: 'babiri-berry', pocket: 'bayas', gens: [4,5], effect: 'items.babiri-berry.effect' },
  { id: 'chilan-berry', name: 'Baya Chilan', sprite: 'chilan-berry', pocket: 'bayas', gens: [4,5], effect: 'items.chilan-berry.effect' },
  // Bayas competitivas (boost con PS bajos)
  { id: 'liechi-berry', name: 'Baya Lichi', sprite: 'liechi-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.liechi-berry.effect' },
  { id: 'ganlon-berry', name: 'Baya Gonlan', sprite: 'ganlon-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.ganlon-berry.effect' },
  { id: 'salac-berry', name: 'Baya Aslac', sprite: 'salac-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.salac-berry.effect' },
  { id: 'petaya-berry', name: 'Baya Pitaya', sprite: 'petaya-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.petaya-berry.effect' },
  { id: 'apicot-berry', name: 'Baya Aricoc', sprite: 'apicot-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.apicot-berry.effect' },
  { id: 'lansat-berry', name: 'Baya Zonlan', sprite: 'lansat-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.lansat-berry.effect' },
  { id: 'starf-berry', name: 'Baya Arabol', sprite: 'starf-berry', pocket: 'bayas', gens: [3,4,5], effect: 'items.starf-berry.effect' },
  { id: 'enigma-berry', name: 'Baya Enigma', sprite: 'enigma-berry', pocket: 'bayas', gens: [4,5], effect: 'items.enigma-berry.effect' },
  { id: 'micle-berry', name: 'Baya Lagro', sprite: 'micle-berry', pocket: 'bayas', gens: [4,5], effect: 'items.micle-berry.effect' },
  { id: 'custap-berry', name: 'Baya Chiri', sprite: 'custap-berry', pocket: 'bayas', gens: [4,5], effect: 'items.custap-berry.effect' },
  { id: 'jaboca-berry', name: 'Baya Jaboca', sprite: 'jaboca-berry', pocket: 'bayas', gens: [4,5], effect: 'items.jaboca-berry.effect' },
  { id: 'rowap-berry', name: 'Baya Rowan', sprite: 'rowap-berry', pocket: 'bayas', gens: [4,5], effect: 'items.rowap-berry.effect' },
];

export const GEMA_ITEMS = [
  { id: 'fire-gem', name: 'Gema Fuego', sprite: 'fire-gem', pocket: 'objetos', gens: [5], effect: 'items.fire-gem.effect' },
  { id: 'water-gem', name: 'Gema Agua', sprite: 'water-gem', pocket: 'objetos', gens: [5], effect: 'items.water-gem.effect' },
  { id: 'electric-gem', name: 'Gema Eléctrica', sprite: 'electric-gem', pocket: 'objetos', gens: [5], effect: 'items.electric-gem.effect' },
  { id: 'grass-gem', name: 'Gema Planta', sprite: 'grass-gem', pocket: 'objetos', gens: [5], effect: 'items.grass-gem.effect' },
  { id: 'ice-gem', name: 'Gema Hielo', sprite: 'ice-gem', pocket: 'objetos', gens: [5], effect: 'items.ice-gem.effect' },
  { id: 'fighting-gem', name: 'Gema Lucha', sprite: 'fighting-gem', pocket: 'objetos', gens: [5], effect: 'items.fighting-gem.effect' },
  { id: 'poison-gem', name: 'Gema Veneno', sprite: 'poison-gem', pocket: 'objetos', gens: [5], effect: 'items.poison-gem.effect' },
  { id: 'ground-gem', name: 'Gema Tierra', sprite: 'ground-gem', pocket: 'objetos', gens: [5], effect: 'items.ground-gem.effect' },
  { id: 'flying-gem', name: 'Gema Voladora', sprite: 'flying-gem', pocket: 'objetos', gens: [5], effect: 'items.flying-gem.effect' },
  { id: 'psychic-gem', name: 'Gema Psíquica', sprite: 'psychic-gem', pocket: 'objetos', gens: [5], effect: 'items.psychic-gem.effect' },
  { id: 'bug-gem', name: 'Gema Bicho', sprite: 'bug-gem', pocket: 'objetos', gens: [5], effect: 'items.bug-gem.effect' },
  { id: 'rock-gem', name: 'Gema Roca', sprite: 'rock-gem', pocket: 'objetos', gens: [5], effect: 'items.rock-gem.effect' },
  { id: 'ghost-gem', name: 'Gema Fantasma', sprite: 'ghost-gem', pocket: 'objetos', gens: [5], effect: 'items.ghost-gem.effect' },
  { id: 'dragon-gem', name: 'Gema Dragón', sprite: 'dragon-gem', pocket: 'objetos', gens: [5], effect: 'items.dragon-gem.effect' },
  { id: 'dark-gem', name: 'Gema Siniestra', sprite: 'dark-gem', pocket: 'objetos', gens: [5], effect: 'items.dark-gem.effect' },
  { id: 'steel-gem', name: 'Gema Acero', sprite: 'steel-gem', pocket: 'objetos', gens: [5], effect: 'items.steel-gem.effect' },
  { id: 'normal-gem', name: 'Gema Normal', sprite: 'normal-gem', pocket: 'objetos', gens: [5], effect: 'items.normal-gem.effect' },
];

export const CLAVE_ITEMS = [
  { id: 'bicycle', name: 'Bicicleta', sprite: 'bicycle', pocket: 'objetos_clave', gens: [1,2,3,4,5], effect: 'items.bicycle.effect' },
  { id: 'old-rod', name: 'Caña Vieja', sprite: 'old-rod', pocket: 'objetos_clave', gens: [1,2,3,4,5], effect: 'items.old-rod.effect' },
  { id: 'good-rod', name: 'Caña Buena', sprite: 'good-rod', pocket: 'objetos_clave', gens: [1,2,3,4,5], effect: 'items.good-rod.effect' },
  { id: 'super-rod', name: 'Supercaña', sprite: 'super-rod', pocket: 'objetos_clave', gens: [1,2,3,4,5], effect: 'items.super-rod.effect' },
  { id: 'town-map', name: 'Mapa', sprite: 'town-map', pocket: 'objetos_clave', gens: [1,2,3,4,5], effect: 'items.town-map.effect' },
  { id: 'vs-seeker', name: 'Buscapelea', sprite: 'vs-seeker', pocket: 'objetos_clave', gens: [1,3,4], effect: 'items.vs-seeker.effect' },
  { id: 'coin-case', name: 'Monedero', sprite: 'coin-case', pocket: 'objetos_clave', gens: [1,2,3,4], effect: 'items.coin-case.effect' },
  { id: 'dowsing-machine', name: 'Zahorí', sprite: 'dowsing-machine', pocket: 'objetos_clave', gens: [4,5], effect: 'items.dowsing-machine.effect' },
  { id: 'ss-ticket', name: 'Billete S.S.', sprite: 'ss-ticket', pocket: 'objetos_clave', gens: [1,2], effect: 'items.ss-ticket.effect' },
  { id: 'poke-flute', name: 'Poké Flauta', sprite: 'poke-flute', pocket: 'objetos_clave', gens: [1], effect: 'items.poke-flute.effect' },
  { id: 'silph-scope', name: 'Scope Silph', sprite: 'silph-scope', pocket: 'objetos_clave', gens: [1], effect: 'items.silph-scope.effect' },
  { id: 'poke-radar', name: 'Poké Radar', sprite: 'poke-radar', pocket: 'objetos_clave', gens: [4], effect: 'items.poke-radar.effect' },
  { id: 'explorer-kit', name: 'Kit Explorador', sprite: 'explorer-kit', pocket: 'objetos_clave', gens: [4], effect: 'items.explorer-kit.effect' },
  { id: 'sprayduck', name: 'Regadera', sprite: 'sprayduck', pocket: 'objetos_clave', gens: [4], effect: 'items.sprayduck.effect' },
  { id: 'squirt-bottle', name: 'Botella Squirt', sprite: 'squirt-bottle', pocket: 'objetos_clave', gens: [2], effect: 'items.squirt-bottle.effect' },
  { id: 'apricorn-box', name: 'Caja Bonguri', sprite: 'apricorn-box', pocket: 'objetos_clave', gens: [2], effect: 'items.apricorn-box.effect' },
  { id: 'wailmer-pail', name: 'Regadera Wailmer', sprite: 'wailmer-pail', pocket: 'objetos_clave', gens: [3], effect: 'items.wailmer-pail.effect' },
  { id: 'mach-bike', name: 'Bici Carreras', sprite: 'mach-bike', pocket: 'objetos_clave', gens: [3], effect: 'items.mach-bike.effect' },
  { id: 'acro-bike', name: 'Bici Acrobática', sprite: 'acro-bike', pocket: 'objetos_clave', gens: [3], effect: 'items.acro-bike.effect' },
  { id: 'go-goggles', name: 'Gafas Protectoras', sprite: 'go-goggles', pocket: 'objetos_clave', gens: [3], effect: 'items.go-goggles.effect' },
  { id: 'devon-scope', name: 'Devon Scope', sprite: 'devon-scope', pocket: 'objetos_clave', gens: [3], effect: 'items.devon-scope.effect' },
  { id: 'vs-recorder', name: 'Grabadora VS', sprite: 'vs-recorder', pocket: 'objetos_clave', gens: [4,5], effect: 'items.vs-recorder.effect' },
  { id: 'pal-pad', name: 'Libreta Amigos', sprite: 'pal-pad', pocket: 'objetos_clave', gens: [4], effect: 'items.pal-pad.effect' },
  { id: 'gracidea', name: 'Gracídea', sprite: 'gracidea', pocket: 'objetos_clave', gens: [4,5], effect: 'items.gracidea.effect' },
  { id: 'prop-case', name: 'Estuche Props', sprite: 'prop-case', pocket: 'objetos_clave', gens: [5], effect: 'items.prop-case.effect' },
  { id: 'xtransceiver', name: 'Videomisor', sprite: 'xtransceiver', pocket: 'objetos_clave', gens: [5], effect: 'items.xtransceiver.effect' },
  { id: 'medal-box', name: 'Caja Medallas', sprite: 'medal-box', pocket: 'objetos_clave', gens: [5], effect: 'items.medal-box.effect' },
  { id: 'dna-splicers', name: 'Punta ADN', sprite: 'dna-splicers', pocket: 'objetos_clave', gens: [5], effect: 'items.dna-splicers.effect' },
  { id: 'reveal-glass', name: 'Espejo Veraz', sprite: 'reveal-glass', pocket: 'objetos_clave', gens: [5], effect: 'items.reveal-glass.effect' },
];
