// ===== CATÁLOGO COMPLETO DE OBJETOS (Gen 1-5) - Parte 2: Objetos generales y equipables =====

export const OBJETOS_ITEMS = [
  // Repelentes y utilidad
  { id: 'escape-rope', name: 'Cuerda Huida', sprite: 'escape-rope', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.escape-rope.effect' },
  { id: 'repel', name: 'Repelente', sprite: 'repel', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.repel.effect' },
  { id: 'super-repel', name: 'Superrepel', sprite: 'super-repel', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.super-repel.effect' },
  { id: 'max-repel', name: 'Repel Máximo', sprite: 'max-repel', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.max-repel.effect' },
  { id: 'honey', name: 'Miel', sprite: 'honey', pocket: 'objetos', gens: [4,5], effect: 'items.honey.effect' },
  // Piedras evolutivas
  { id: 'fire-stone', name: 'Piedra Fuego', sprite: 'fire-stone', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.fire-stone.effect' },
  { id: 'water-stone', name: 'Piedra Agua', sprite: 'water-stone', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.water-stone.effect' },
  { id: 'thunder-stone', name: 'Piedra Trueno', sprite: 'thunder-stone', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.thunder-stone.effect' },
  { id: 'leaf-stone', name: 'Piedra Hoja', sprite: 'leaf-stone', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.leaf-stone.effect' },
  { id: 'moon-stone', name: 'Piedra Lunar', sprite: 'moon-stone', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.moon-stone.effect' },
  { id: 'sun-stone', name: 'Piedra Solar', sprite: 'sun-stone', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.sun-stone.effect' },
  { id: 'shiny-stone', name: 'Piedra Día', sprite: 'shiny-stone', pocket: 'objetos', gens: [4,5], effect: 'items.shiny-stone.effect' },
  { id: 'dusk-stone', name: 'Piedra Noche', sprite: 'dusk-stone', pocket: 'objetos', gens: [4,5], effect: 'items.dusk-stone.effect' },
  { id: 'dawn-stone', name: 'Piedra Alba', sprite: 'dawn-stone', pocket: 'objetos', gens: [4,5], effect: 'items.dawn-stone.effect' },
  { id: 'oval-stone', name: 'Piedra Oval', sprite: 'oval-stone', pocket: 'objetos', gens: [4,5], effect: 'items.oval-stone.effect' },
  // Objetos de evolución por intercambio
  { id: 'kings-rock', name: 'Roca del Rey', sprite: 'kings-rock', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.kings-rock.effect' },
  { id: 'metal-coat', name: 'Revestimiento Met.', sprite: 'metal-coat', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.metal-coat.effect' },
  { id: 'dragon-scale', name: 'Escama Dragón', sprite: 'dragon-scale', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.dragon-scale.effect' },
  { id: 'up-grade', name: 'Mejora', sprite: 'up-grade', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.up-grade.effect' },
  { id: 'deep-sea-tooth', name: 'Diente Marino', sprite: 'deep-sea-tooth', pocket: 'objetos', gens: [3,4,5], effect: 'items.deep-sea-tooth.effect' },
  { id: 'deep-sea-scale', name: 'Escama Marina', sprite: 'deep-sea-scale', pocket: 'objetos', gens: [3,4,5], effect: 'items.deep-sea-scale.effect' },
  { id: 'protector', name: 'Protector', sprite: 'protector', pocket: 'objetos', gens: [4,5], effect: 'items.protector.effect' },
  { id: 'electirizer', name: 'Electrizador', sprite: 'electirizer', pocket: 'objetos', gens: [4,5], effect: 'items.electirizer.effect' },
  { id: 'magmarizer', name: 'Magmatizador', sprite: 'magmarizer', pocket: 'objetos', gens: [4,5], effect: 'items.magmarizer.effect' },
  { id: 'dubious-disc', name: 'Disco Extraño', sprite: 'dubious-disc', pocket: 'objetos', gens: [4,5], effect: 'items.dubious-disc.effect' },
  { id: 'reaper-cloth', name: 'Tela Terrible', sprite: 'reaper-cloth', pocket: 'objetos', gens: [4,5], effect: 'items.reaper-cloth.effect' },
  { id: 'razor-claw', name: 'Garra Afilada', sprite: 'razor-claw', pocket: 'objetos', gens: [4,5], effect: 'items.razor-claw.effect' },
  { id: 'razor-fang', name: 'Colmillo Afilado', sprite: 'razor-fang', pocket: 'objetos', gens: [4,5], effect: 'items.razor-fang.effect' },
  { id: 'prism-scale', name: 'Escama Prisma', sprite: 'prism-scale', pocket: 'objetos', gens: [5], effect: 'items.prism-scale.effect' },
  // Vitaminas
  { id: 'hp-up', name: 'Más PS', sprite: 'hp-up', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.hp-up.effect' },
  { id: 'protein', name: 'Proteína', sprite: 'protein', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.protein.effect' },
  { id: 'iron', name: 'Hierro', sprite: 'iron', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.iron.effect' },
  { id: 'calcium', name: 'Calcio', sprite: 'calcium', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.calcium.effect' },
  { id: 'zinc', name: 'Zinc', sprite: 'zinc', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.zinc.effect' },
  { id: 'carbos', name: 'Carburante', sprite: 'carbos', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.carbos.effect' },
  { id: 'pp-up', name: 'Más PP', sprite: 'pp-up', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.pp-up.effect' },
  { id: 'pp-max', name: 'PP Máximo', sprite: 'pp-max', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.pp-max.effect' },
  // Alas (Gen 5)
  { id: 'health-wing', name: 'Pluma Vigor', sprite: 'health-wing', pocket: 'objetos', gens: [5], effect: 'items.health-wing.effect' },
  { id: 'muscle-wing', name: 'Pluma Músculo', sprite: 'muscle-wing', pocket: 'objetos', gens: [5], effect: 'items.muscle-wing.effect' },
  { id: 'resist-wing', name: 'Pluma Aguante', sprite: 'resist-wing', pocket: 'objetos', gens: [5], effect: 'items.resist-wing.effect' },
  { id: 'genius-wing', name: 'Pluma Genio', sprite: 'genius-wing', pocket: 'objetos', gens: [5], effect: 'items.genius-wing.effect' },
  { id: 'clever-wing', name: 'Pluma Astucia', sprite: 'clever-wing', pocket: 'objetos', gens: [5], effect: 'items.clever-wing.effect' },
  { id: 'swift-wing', name: 'Pluma Rapidez', sprite: 'swift-wing', pocket: 'objetos', gens: [5], effect: 'items.swift-wing.effect' },
  // Objetos de venta
  { id: 'nugget', name: 'Pepita', sprite: 'nugget', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.nugget.effect' },
  { id: 'big-nugget', name: 'Pepita Grande', sprite: 'big-nugget', pocket: 'objetos', gens: [5], effect: 'items.big-nugget.effect' },
  { id: 'pearl', name: 'Perla', sprite: 'pearl', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.pearl.effect' },
  { id: 'big-pearl', name: 'Perla Grande', sprite: 'big-pearl', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.big-pearl.effect' },
  { id: 'pearl-string', name: 'Collar de Perlas', sprite: 'pearl-string', pocket: 'objetos', gens: [5], effect: 'items.pearl-string.effect' },
  { id: 'stardust', name: 'Polvo Estelar', sprite: 'stardust', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.stardust.effect' },
  { id: 'star-piece', name: 'Trozo Estrella', sprite: 'star-piece', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.star-piece.effect' },
  { id: 'comet-shard', name: 'Trozo Cometa', sprite: 'comet-shard', pocket: 'objetos', gens: [5], effect: 'items.comet-shard.effect' },
  { id: 'tiny-mushroom', name: 'Miniseta', sprite: 'tiny-mushroom', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.tiny-mushroom.effect' },
  { id: 'big-mushroom', name: 'Seta Grande', sprite: 'big-mushroom', pocket: 'objetos', gens: [1,2,3,4,5], effect: 'items.big-mushroom.effect' },
  { id: 'balm-mushroom', name: 'Seta Aroma', sprite: 'balm-mushroom', pocket: 'objetos', gens: [5], effect: 'items.balm-mushroom.effect' },
  { id: 'rare-bone', name: 'Hueso Raro', sprite: 'rare-bone', pocket: 'objetos', gens: [4,5], effect: 'items.rare-bone.effect' },
  { id: 'heart-scale', name: 'Escama Corazón', sprite: 'heart-scale', pocket: 'objetos', gens: [3,4,5], effect: 'items.heart-scale.effect' },
  // Fragmentos
  { id: 'red-shard', name: 'Trozo Rojo', sprite: 'red-shard', pocket: 'objetos', gens: [3,4,5], effect: 'items.red-shard.effect' },
  { id: 'blue-shard', name: 'Trozo Azul', sprite: 'blue-shard', pocket: 'objetos', gens: [3,4,5], effect: 'items.blue-shard.effect' },
  { id: 'yellow-shard', name: 'Trozo Amarillo', sprite: 'yellow-shard', pocket: 'objetos', gens: [3,4,5], effect: 'items.yellow-shard.effect' },
  { id: 'green-shard', name: 'Trozo Verde', sprite: 'green-shard', pocket: 'objetos', gens: [3,4,5], effect: 'items.green-shard.effect' },
  // Flautas (Gen 3)
  { id: 'blue-flute', name: 'Flauta Azul', sprite: 'blue-flute', pocket: 'objetos', gens: [3,4,5], effect: 'items.blue-flute.effect' },
  { id: 'yellow-flute', name: 'Flauta Amarilla', sprite: 'yellow-flute', pocket: 'objetos', gens: [3,4,5], effect: 'items.yellow-flute.effect' },
  { id: 'red-flute', name: 'Flauta Roja', sprite: 'red-flute', pocket: 'objetos', gens: [3,4,5], effect: 'items.red-flute.effect' },
  { id: 'black-flute', name: 'Flauta Negra', sprite: 'black-flute', pocket: 'objetos', gens: [3,4,5], effect: 'items.black-flute.effect' },
  { id: 'white-flute', name: 'Flauta Blanca', sprite: 'white-flute', pocket: 'objetos', gens: [3,4,5], effect: 'items.white-flute.effect' },
  // Fósiles
  { id: 'helix-fossil', name: 'Fósil Helix', sprite: 'helix-fossil', pocket: 'objetos', gens: [1,3,4,5], effect: 'items.helix-fossil.effect' },
  { id: 'dome-fossil', name: 'Fósil Domo', sprite: 'dome-fossil', pocket: 'objetos', gens: [1,3,4,5], effect: 'items.dome-fossil.effect' },
  { id: 'old-amber', name: 'Ámbar Viejo', sprite: 'old-amber', pocket: 'objetos', gens: [1,3,4,5], effect: 'items.old-amber.effect' },
  { id: 'root-fossil', name: 'Fósil Raíz', sprite: 'root-fossil', pocket: 'objetos', gens: [3,4,5], effect: 'items.root-fossil.effect' },
  { id: 'claw-fossil', name: 'Fósil Garra', sprite: 'claw-fossil', pocket: 'objetos', gens: [3,4,5], effect: 'items.claw-fossil.effect' },
  { id: 'armor-fossil', name: 'Fósil Coraza', sprite: 'armor-fossil', pocket: 'objetos', gens: [4,5], effect: 'items.armor-fossil.effect' },
  { id: 'skull-fossil', name: 'Fósil Cráneo', sprite: 'skull-fossil', pocket: 'objetos', gens: [4,5], effect: 'items.skull-fossil.effect' },
  { id: 'cover-fossil', name: 'Fósil Tapa', sprite: 'cover-fossil', pocket: 'objetos', gens: [5], effect: 'items.cover-fossil.effect' },
  { id: 'plume-fossil', name: 'Fósil Pluma', sprite: 'plume-fossil', pocket: 'objetos', gens: [5], effect: 'items.plume-fossil.effect' },
  // Shoal y Reliquias
  { id: 'shoal-salt', name: 'Sal Cardumen', sprite: 'shoal-salt', pocket: 'objetos', gens: [3,4,5], effect: 'items.shoal-salt.effect' },
  { id: 'shoal-shell', name: 'Concha Cardumen', sprite: 'shoal-shell', pocket: 'objetos', gens: [3,4,5], effect: 'items.shoal-shell.effect' },
  { id: 'relic-copper', name: 'Reliquia Cobre', sprite: 'relic-copper', pocket: 'objetos', gens: [5], effect: 'items.relic-copper.effect' },
  { id: 'relic-silver', name: 'Reliquia Plata', sprite: 'relic-silver', pocket: 'objetos', gens: [5], effect: 'items.relic-silver.effect' },
  { id: 'relic-gold', name: 'Reliquia Oro', sprite: 'relic-gold', pocket: 'objetos', gens: [5], effect: 'items.relic-gold.effect' },
  { id: 'relic-vase', name: 'Reliquia Jarrón', sprite: 'relic-vase', pocket: 'objetos', gens: [5], effect: 'items.relic-vase.effect' },
  { id: 'relic-band', name: 'Reliquia Banda', sprite: 'relic-band', pocket: 'objetos', gens: [5], effect: 'items.relic-band.effect' },
  { id: 'relic-statue', name: 'Reliquia Estatua', sprite: 'relic-statue', pocket: 'objetos', gens: [5], effect: 'items.relic-statue.effect' },
  { id: 'relic-crown', name: 'Reliquia Corona', sprite: 'relic-crown', pocket: 'objetos', gens: [5], effect: 'items.relic-crown.effect' },
  // Held Items - Competitivo / Utilidad
  { id: 'leftovers', name: 'Restos', sprite: 'leftovers', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.leftovers.effect' },
  { id: 'shell-bell', name: 'Campana Concha', sprite: 'shell-bell', pocket: 'objetos', gens: [3,4,5], effect: 'items.shell-bell.effect' },
  { id: 'lucky-egg', name: 'Huevo Suerte', sprite: 'lucky-egg', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.lucky-egg.effect' },
  { id: 'amulet-coin', name: 'Moneda Amuleto', sprite: 'amulet-coin', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.amulet-coin.effect' },
  { id: 'exp-share', name: 'Repartir Exp.', sprite: 'exp-share', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.exp-share.effect' },
  { id: 'everstone', name: 'Piedra Eterna', sprite: 'everstone', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.everstone.effect' },
  { id: 'smoke-ball', name: 'Bola Humo', sprite: 'smoke-ball', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.smoke-ball.effect' },
  { id: 'bright-powder', name: 'Polvo Brillo', sprite: 'bright-powder', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.bright-powder.effect' },
  { id: 'white-herb', name: 'Hierba Blanca', sprite: 'white-herb', pocket: 'objetos', gens: [3,4,5], effect: 'items.white-herb.effect' },
  { id: 'mental-herb', name: 'Hierba Mental', sprite: 'mental-herb', pocket: 'objetos', gens: [3,4,5], effect: 'items.mental-herb.effect' },
  { id: 'power-herb', name: 'Hierba Única', sprite: 'power-herb', pocket: 'objetos', gens: [4,5], effect: 'items.power-herb.effect' },
  { id: 'macho-brace', name: 'Brazal Firme', sprite: 'macho-brace', pocket: 'objetos', gens: [3,4,5], effect: 'items.macho-brace.effect' },
  { id: 'quick-claw', name: 'Garra Rápida', sprite: 'quick-claw', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.quick-claw.effect' },
  { id: 'soothe-bell', name: 'Campana Alivio', sprite: 'soothe-bell', pocket: 'objetos', gens: [3,4,5], effect: 'items.soothe-bell.effect' },
  { id: 'cleanse-tag', name: 'Amuleto Puro', sprite: 'cleanse-tag', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.cleanse-tag.effect' },
  { id: 'soul-dew', name: 'Rocío Bondad', sprite: 'soul-dew', pocket: 'objetos', gens: [3,4,5], effect: 'items.soul-dew.effect' },
  { id: 'scope-lens', name: 'Lupa', sprite: 'scope-lens', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.scope-lens.effect' },
  { id: 'wide-lens', name: 'Lente Gran Angular', sprite: 'wide-lens', pocket: 'objetos', gens: [4,5], effect: 'items.wide-lens.effect' },
  { id: 'zoom-lens', name: 'Lente Zoom', sprite: 'zoom-lens', pocket: 'objetos', gens: [4,5], effect: 'items.zoom-lens.effect' },
  { id: 'muscle-band', name: 'Cinta Fuerte', sprite: 'muscle-band', pocket: 'objetos', gens: [4,5], effect: 'items.muscle-band.effect' },
  { id: 'wise-glasses', name: 'Gafas Especiales', sprite: 'wise-glasses', pocket: 'objetos', gens: [4,5], effect: 'items.wise-glasses.effect' },
  { id: 'expert-belt', name: 'Cinta Experto', sprite: 'expert-belt', pocket: 'objetos', gens: [4,5], effect: 'items.expert-belt.effect' },
  { id: 'life-orb', name: 'Vidasfera', sprite: 'life-orb', pocket: 'objetos', gens: [4,5], effect: 'items.life-orb.effect' },
  { id: 'choice-band', name: 'Cinta Elegida', sprite: 'choice-band', pocket: 'objetos', gens: [3,4,5], effect: 'items.choice-band.effect' },
  { id: 'choice-specs', name: 'Gafas Elegidas', sprite: 'choice-specs', pocket: 'objetos', gens: [4,5], effect: 'items.choice-specs.effect' },
  { id: 'choice-scarf', name: 'Pañuelo Elegido', sprite: 'choice-scarf', pocket: 'objetos', gens: [4,5], effect: 'items.choice-scarf.effect' },
  { id: 'focus-sash', name: 'Banda Focus', sprite: 'focus-sash', pocket: 'objetos', gens: [4,5], effect: 'items.focus-sash.effect' },
  { id: 'focus-band', name: 'Cinta Focus', sprite: 'focus-band', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.focus-band.effect' },
  { id: 'metronome', name: 'Metrónomo', sprite: 'metronome', pocket: 'objetos', gens: [4,5], effect: 'items.metronome.effect' },
  { id: 'iron-ball', name: 'Bola de Hierro', sprite: 'iron-ball', pocket: 'objetos', gens: [4,5], effect: 'items.iron-ball.effect' },
  { id: 'lagging-tail', name: 'Cola Lenta', sprite: 'lagging-tail', pocket: 'objetos', gens: [4,5], effect: 'items.lagging-tail.effect' },
  { id: 'destiny-knot', name: 'Lazo Destino', sprite: 'destiny-knot', pocket: 'objetos', gens: [4,5], effect: 'items.destiny-knot.effect' },
  { id: 'black-sludge', name: 'Lodo Negro', sprite: 'black-sludge', pocket: 'objetos', gens: [4,5], effect: 'items.black-sludge.effect' },
  { id: 'toxic-orb', name: 'Toxiesfera', sprite: 'toxic-orb', pocket: 'objetos', gens: [4,5], effect: 'items.toxic-orb.effect' },
  { id: 'flame-orb', name: 'Flamosfera', sprite: 'flame-orb', pocket: 'objetos', gens: [4,5], effect: 'items.flame-orb.effect' },
  { id: 'light-clay', name: 'Roca Luz', sprite: 'light-clay', pocket: 'objetos', gens: [4,5], effect: 'items.light-clay.effect' },
  { id: 'icy-rock', name: 'Roca Helada', sprite: 'icy-rock', pocket: 'objetos', gens: [4,5], effect: 'items.icy-rock.effect' },
  { id: 'smooth-rock', name: 'Roca Suave', sprite: 'smooth-rock', pocket: 'objetos', gens: [4,5], effect: 'items.smooth-rock.effect' },
  { id: 'heat-rock', name: 'Roca Caliente', sprite: 'heat-rock', pocket: 'objetos', gens: [4,5], effect: 'items.heat-rock.effect' },
  { id: 'damp-rock', name: 'Roca Húmeda', sprite: 'damp-rock', pocket: 'objetos', gens: [4,5], effect: 'items.damp-rock.effect' },
  { id: 'grip-claw', name: 'Garra Tenaza', sprite: 'grip-claw', pocket: 'objetos', gens: [4,5], effect: 'items.grip-claw.effect' },
  { id: 'sticky-barb', name: 'Púas Adherentes', sprite: 'sticky-barb', pocket: 'objetos', gens: [4,5], effect: 'items.sticky-barb.effect' },
  { id: 'shed-shell', name: 'Muda Concha', sprite: 'shed-shell', pocket: 'objetos', gens: [4,5], effect: 'items.shed-shell.effect' },
  { id: 'big-root', name: 'Raíz Grande', sprite: 'big-root', pocket: 'objetos', gens: [4,5], effect: 'items.big-root.effect' },
  // Gen 5 held items competitivos
  { id: 'eviolite', name: 'Mineral Evol.', sprite: 'eviolite', pocket: 'objetos', gens: [5], effect: 'items.eviolite.effect' },
  { id: 'rocky-helmet', name: 'Casco Dentado', sprite: 'rocky-helmet', pocket: 'objetos', gens: [5], effect: 'items.rocky-helmet.effect' },
  { id: 'air-balloon', name: 'Globo Helio', sprite: 'air-balloon', pocket: 'objetos', gens: [5], effect: 'items.air-balloon.effect' },
  { id: 'red-card', name: 'Tarjeta Roja', sprite: 'red-card', pocket: 'objetos', gens: [5], effect: 'items.red-card.effect' },
  { id: 'ring-target', name: 'Blanco', sprite: 'ring-target', pocket: 'objetos', gens: [5], effect: 'items.ring-target.effect' },
  { id: 'binding-band', name: 'Banda Atadura', sprite: 'binding-band', pocket: 'objetos', gens: [5], effect: 'items.binding-band.effect' },
  { id: 'absorb-bulb', name: 'Bulbo Absorbente', sprite: 'absorb-bulb', pocket: 'objetos', gens: [5], effect: 'items.absorb-bulb.effect' },
  { id: 'cell-battery', name: 'Pila', sprite: 'cell-battery', pocket: 'objetos', gens: [5], effect: 'items.cell-battery.effect' },
  { id: 'eject-button', name: 'Botón Escape', sprite: 'eject-button', pocket: 'objetos', gens: [5], effect: 'items.eject-button.effect' },
  { id: 'float-stone', name: 'Piedra Pómez', sprite: 'float-stone', pocket: 'objetos', gens: [5], effect: 'items.float-stone.effect' },
  // Potenciadores de tipo
  { id: 'silk-scarf', name: 'Pañuelo Seda', sprite: 'silk-scarf', pocket: 'objetos', gens: [3,4,5], effect: 'items.silk-scarf.effect' },
  { id: 'black-belt', name: 'Cinturón Negro', sprite: 'black-belt', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.black-belt.effect' },
  { id: 'charcoal', name: 'Carbón', sprite: 'charcoal', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.charcoal.effect' },
  { id: 'mystic-water', name: 'Agua Mística', sprite: 'mystic-water', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.mystic-water.effect' },
  { id: 'magnet', name: 'Imán', sprite: 'magnet', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.magnet.effect' },
  { id: 'miracle-seed', name: 'Semilla Milagro', sprite: 'miracle-seed', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.miracle-seed.effect' },
  { id: 'never-melt-ice', name: 'Hielo Eterno', sprite: 'never-melt-ice', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.never-melt-ice.effect' },
  { id: 'soft-sand', name: 'Arena Fina', sprite: 'soft-sand', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.soft-sand.effect' },
  { id: 'hard-stone', name: 'Piedra Dura', sprite: 'hard-stone', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.hard-stone.effect' },
  { id: 'sharp-beak', name: 'Pico Afilado', sprite: 'sharp-beak', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.sharp-beak.effect' },
  { id: 'poison-barb', name: 'Púa Venenosa', sprite: 'poison-barb', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.poison-barb.effect' },
  { id: 'spell-tag', name: 'Hechizo', sprite: 'spell-tag', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.spell-tag.effect' },
  { id: 'twisted-spoon', name: 'Cuchara Torcida', sprite: 'twisted-spoon', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.twisted-spoon.effect' },
  { id: 'dragon-fang', name: 'Colmillo Dragón', sprite: 'dragon-fang', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.dragon-fang.effect' },
  { id: 'black-glasses', name: 'Gafas de Sol', sprite: 'black-glasses', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.black-glasses.effect' },
  { id: 'silver-powder', name: 'Polvo Plata', sprite: 'silver-powder', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.silver-powder.effect' },
  { id: 'light-ball', name: 'Bola Luminosa', sprite: 'light-ball', pocket: 'objetos', gens: [2,3,4,5], effect: 'items.light-ball.effect' },
  // Inciensos
  { id: 'sea-incense', name: 'Incienso Marino', sprite: 'sea-incense', pocket: 'objetos', gens: [3,4,5], effect: 'items.sea-incense.effect' },
  { id: 'lax-incense', name: 'Incienso Suave', sprite: 'lax-incense', pocket: 'objetos', gens: [3,4,5], effect: 'items.lax-incense.effect' },
  { id: 'odd-incense', name: 'Incienso Raro', sprite: 'odd-incense', pocket: 'objetos', gens: [4,5], effect: 'items.odd-incense.effect' },
  { id: 'rock-incense', name: 'Incienso Roca', sprite: 'rock-incense', pocket: 'objetos', gens: [4,5], effect: 'items.rock-incense.effect' },
  { id: 'full-incense', name: 'Incienso Lento', sprite: 'full-incense', pocket: 'objetos', gens: [4,5], effect: 'items.full-incense.effect' },
  { id: 'wave-incense', name: 'Incienso Ola', sprite: 'wave-incense', pocket: 'objetos', gens: [4,5], effect: 'items.wave-incense.effect' },
  { id: 'rose-incense', name: 'Incienso Floral', sprite: 'rose-incense', pocket: 'objetos', gens: [4,5], effect: 'items.rose-incense.effect' },
  { id: 'luck-incense', name: 'Incienso Suerte', sprite: 'luck-incense', pocket: 'objetos', gens: [4,5], effect: 'items.luck-incense.effect' },
  { id: 'pure-incense', name: 'Incienso Puro', sprite: 'pure-incense', pocket: 'objetos', gens: [4,5], effect: 'items.pure-incense.effect' },
  // Power items (EV)
  { id: 'power-weight', name: 'Pesa Recia', sprite: 'power-weight', pocket: 'objetos', gens: [4,5], effect: 'items.power-weight.effect' },
  { id: 'power-bracer', name: 'Brazal Recio', sprite: 'power-bracer', pocket: 'objetos', gens: [4,5], effect: 'items.power-bracer.effect' },
  { id: 'power-belt', name: 'Cinto Recio', sprite: 'power-belt', pocket: 'objetos', gens: [4,5], effect: 'items.power-belt.effect' },
  { id: 'power-lens', name: 'Lente Recia', sprite: 'power-lens', pocket: 'objetos', gens: [4,5], effect: 'items.power-lens.effect' },
  { id: 'power-band', name: 'Banda Recia', sprite: 'power-band', pocket: 'objetos', gens: [4,5], effect: 'items.power-band.effect' },
  { id: 'power-anklet', name: 'Franja Recia', sprite: 'power-anklet', pocket: 'objetos', gens: [4,5], effect: 'items.power-anklet.effect' },
  // Placas de Arceus
  { id: 'flame-plate', name: 'Tabla Llama', sprite: 'flame-plate', pocket: 'objetos', gens: [4,5], effect: 'items.flame-plate.effect' },
  { id: 'splash-plate', name: 'Tabla Linfa', sprite: 'splash-plate', pocket: 'objetos', gens: [4,5], effect: 'items.splash-plate.effect' },
  { id: 'zap-plate', name: 'Tabla Trueno', sprite: 'zap-plate', pocket: 'objetos', gens: [4,5], effect: 'items.zap-plate.effect' },
  { id: 'meadow-plate', name: 'Tabla Pradera', sprite: 'meadow-plate', pocket: 'objetos', gens: [4,5], effect: 'items.meadow-plate.effect' },
  { id: 'icicle-plate', name: 'Tabla Helada', sprite: 'icicle-plate', pocket: 'objetos', gens: [4,5], effect: 'items.icicle-plate.effect' },
  { id: 'fist-plate', name: 'Tabla Puño', sprite: 'fist-plate', pocket: 'objetos', gens: [4,5], effect: 'items.fist-plate.effect' },
  { id: 'toxic-plate', name: 'Tabla Tóxica', sprite: 'toxic-plate', pocket: 'objetos', gens: [4,5], effect: 'items.toxic-plate.effect' },
  { id: 'earth-plate', name: 'Tabla Terrax', sprite: 'earth-plate', pocket: 'objetos', gens: [4,5], effect: 'items.earth-plate.effect' },
  { id: 'sky-plate', name: 'Tabla Cielo', sprite: 'sky-plate', pocket: 'objetos', gens: [4,5], effect: 'items.sky-plate.effect' },
  { id: 'mind-plate', name: 'Tabla Mental', sprite: 'mind-plate', pocket: 'objetos', gens: [4,5], effect: 'items.mind-plate.effect' },
  { id: 'insect-plate', name: 'Tabla Bicho', sprite: 'insect-plate', pocket: 'objetos', gens: [4,5], effect: 'items.insect-plate.effect' },
  { id: 'stone-plate', name: 'Tabla Pétrea', sprite: 'stone-plate', pocket: 'objetos', gens: [4,5], effect: 'items.stone-plate.effect' },
  { id: 'spooky-plate', name: 'Tabla Terror', sprite: 'spooky-plate', pocket: 'objetos', gens: [4,5], effect: 'items.spooky-plate.effect' },
  { id: 'draco-plate', name: 'Tabla Draco', sprite: 'draco-plate', pocket: 'objetos', gens: [4,5], effect: 'items.draco-plate.effect' },
  { id: 'dread-plate', name: 'Tabla Oscura', sprite: 'dread-plate', pocket: 'objetos', gens: [4,5], effect: 'items.dread-plate.effect' },
  { id: 'iron-plate', name: 'Tabla Férrea', sprite: 'iron-plate', pocket: 'objetos', gens: [4,5], effect: 'items.iron-plate.effect' },
  // Orbes legendarios
  { id: 'adamant-orb', name: 'Diamansfera', sprite: 'adamant-orb', pocket: 'objetos', gens: [4,5], effect: 'items.adamant-orb.effect' },
  { id: 'lustrous-orb', name: 'Lustresfera', sprite: 'lustrous-orb', pocket: 'objetos', gens: [4,5], effect: 'items.lustrous-orb.effect' },
  { id: 'griseous-orb', name: 'Griseosfera', sprite: 'griseous-orb', pocket: 'objetos', gens: [4,5], effect: 'items.griseous-orb.effect' },
  // Drives de Genesect (Gen 5)
  { id: 'douse-drive', name: 'HidroROM', sprite: 'douse-drive', pocket: 'objetos', gens: [5], effect: 'items.douse-drive.effect' },
  { id: 'shock-drive', name: 'FulgoROM', sprite: 'shock-drive', pocket: 'objetos', gens: [5], effect: 'items.shock-drive.effect' },
  { id: 'burn-drive', name: 'PiroROM', sprite: 'burn-drive', pocket: 'objetos', gens: [5], effect: 'items.burn-drive.effect' },
  { id: 'chill-drive', name: 'CrioROM', sprite: 'chill-drive', pocket: 'objetos', gens: [5], effect: 'items.chill-drive.effect' },
];
